const keys = [
  "title",
  "intro",
  "profile",
  "preferences",
  "socials",
  "displayName",
  "username",
  "language",
  "timeZone",
  "website",
  "socialHelp",
  "optional",
  "back",
  "next",
  "finish",
  "save",
  "loading",
  "saving",
  "loadError",
  "saveError",
  "conflict",
  "retry",
  "done",
  "nameRequired",
  "dashboard",
] as const;
type Copy = Record<(typeof keys)[number], string>;
const translations: Record<string, string[]> = {
  en: [
    "Your PerkOS profile",
    "Set up your account. No project or agent will be created.",
    "Profile",
    "Preferences",
    "Social profiles",
    "Display name",
    "Username",
    "Language",
    "Time zone",
    "Website",
    "Links only. We do not connect your accounts or publish anything. These are your personal profiles, not your project's accounts.",
    "Optional",
    "Back",
    "Continue",
    "Finish setup",
    "Save profile",
    "Loading profile…",
    "Saving…",
    "Could not load your profile.",
    "Could not save. Check the fields and use valid HTTPS links or social handles.",
    "Your profile changed elsewhere. Reload before saving.",
    "Reload",
    "Profile saved",
    "Enter your display name.",
    "Go to dashboard",
  ],
  es: [
    "Tu perfil de PerkOS",
    "Configura tu cuenta. No se creará ningún proyecto ni agente.",
    "Perfil",
    "Preferencias",
    "Perfiles sociales",
    "Nombre visible",
    "Nombre de usuario",
    "Idioma",
    "Zona horaria",
    "Sitio web",
    "Solo enlaces. No conectamos tus cuentas ni publicamos contenido. Son tus perfiles personales, no las cuentas de tu proyecto.",
    "Opcional",
    "Atrás",
    "Continuar",
    "Finalizar configuración",
    "Guardar perfil",
    "Cargando perfil…",
    "Guardando…",
    "No se pudo cargar tu perfil.",
    "No se pudo guardar. Revisa los campos y usa enlaces HTTPS o usuarios sociales válidos.",
    "Tu perfil cambió en otro lugar. Recarga antes de guardar.",
    "Recargar",
    "Perfil guardado",
    "Introduce tu nombre visible.",
    "Ir al panel",
  ],
  fr: [
    "Votre profil PerkOS",
    "Configurez votre compte. Aucun projet ni agent ne sera créé.",
    "Profil",
    "Préférences",
    "Profils sociaux",
    "Nom affiché",
    "Nom d’utilisateur",
    "Langue",
    "Fuseau horaire",
    "Site web",
    "Liens uniquement. Nous ne connectons pas vos comptes et ne publions rien. Ce sont vos profils personnels, pas ceux du projet.",
    "Facultatif",
    "Retour",
    "Continuer",
    "Terminer",
    "Enregistrer le profil",
    "Chargement du profil…",
    "Enregistrement…",
    "Impossible de charger votre profil.",
    "Échec de l’enregistrement. Vérifiez les champs et les liens HTTPS ou identifiants sociaux.",
    "Votre profil a été modifié ailleurs. Rechargez avant d’enregistrer.",
    "Recharger",
    "Profil enregistré",
    "Saisissez votre nom affiché.",
    "Aller au tableau de bord",
  ],
  pt: [
    "Seu perfil PerkOS",
    "Configure sua conta. Nenhum projeto ou agente será criado.",
    "Perfil",
    "Preferências",
    "Perfis sociais",
    "Nome de exibição",
    "Nome de usuário",
    "Idioma",
    "Fuso horário",
    "Site",
    "Apenas links. Não conectamos suas contas nem publicamos conteúdo. São seus perfis pessoais, não as contas do projeto.",
    "Opcional",
    "Voltar",
    "Continuar",
    "Concluir configuração",
    "Salvar perfil",
    "Carregando perfil…",
    "Salvando…",
    "Não foi possível carregar seu perfil.",
    "Não foi possível salvar. Confira os campos e os links HTTPS ou usuários sociais.",
    "Seu perfil mudou em outro lugar. Recarregue antes de salvar.",
    "Recarregar",
    "Perfil salvo",
    "Informe seu nome de exibição.",
    "Ir ao painel",
  ],
  it: [
    "Il tuo profilo PerkOS",
    "Configura il tuo account. Non verranno creati progetti o agenti.",
    "Profilo",
    "Preferenze",
    "Profili social",
    "Nome visualizzato",
    "Nome utente",
    "Lingua",
    "Fuso orario",
    "Sito web",
    "Solo link. Non colleghiamo account e non pubblichiamo contenuti. Sono i tuoi profili personali, non quelli del progetto.",
    "Facoltativo",
    "Indietro",
    "Continua",
    "Completa configurazione",
    "Salva profilo",
    "Caricamento profilo…",
    "Salvataggio…",
    "Impossibile caricare il profilo.",
    "Impossibile salvare. Controlla i campi e i link HTTPS o nomi social.",
    "Il profilo è cambiato altrove. Ricarica prima di salvare.",
    "Ricarica",
    "Profilo salvato",
    "Inserisci il nome visualizzato.",
    "Vai al pannello",
  ],
  ja: [
    "PerkOSプロフィール",
    "アカウントを設定します。プロジェクトやエージェントは作成されません。",
    "プロフィール",
    "設定",
    "SNSプロフィール",
    "表示名",
    "ユーザー名",
    "言語",
    "タイムゾーン",
    "ウェブサイト",
    "リンクのみ保存します。アカウント接続や投稿は行いません。プロジェクト用ではなく個人のプロフィールです。",
    "任意",
    "戻る",
    "次へ",
    "設定を完了",
    "プロフィールを保存",
    "読み込み中…",
    "保存中…",
    "プロフィールを読み込めませんでした。",
    "保存できませんでした。入力内容とHTTPSリンクまたはSNSユーザー名を確認してください。",
    "別の場所で変更されました。保存前に再読み込みしてください。",
    "再読み込み",
    "保存しました",
    "表示名を入力してください。",
    "ダッシュボードへ",
  ],
  ko: [
    "PerkOS 프로필",
    "계정을 설정하세요. 프로젝트나 에이전트는 생성되지 않습니다.",
    "프로필",
    "환경설정",
    "소셜 프로필",
    "표시 이름",
    "사용자 이름",
    "언어",
    "시간대",
    "웹사이트",
    "링크만 저장합니다. 계정을 연결하거나 게시하지 않습니다. 프로젝트 계정이 아닌 개인 프로필입니다.",
    "선택 사항",
    "뒤로",
    "계속",
    "설정 완료",
    "프로필 저장",
    "프로필 불러오는 중…",
    "저장 중…",
    "프로필을 불러오지 못했습니다.",
    "저장하지 못했습니다. 입력값과 HTTPS 링크 또는 소셜 사용자 이름을 확인하세요.",
    "다른 곳에서 프로필이 변경되었습니다. 저장하기 전에 새로고침하세요.",
    "새로고침",
    "프로필 저장됨",
    "표시 이름을 입력하세요.",
    "대시보드로 이동",
  ],
  zh: [
    "你的 PerkOS 个人资料",
    "设置账户，不会创建项目或智能体。",
    "个人资料",
    "偏好设置",
    "社交资料",
    "显示名称",
    "用户名",
    "语言",
    "时区",
    "网站",
    "仅保存链接，不连接账户或发布内容。这些是个人资料，不是项目账户。",
    "可选",
    "返回",
    "继续",
    "完成设置",
    "保存资料",
    "正在加载资料…",
    "正在保存…",
    "无法加载资料。",
    "无法保存。请检查字段及 HTTPS 链接或社交用户名。",
    "资料已在其他位置更改，请重新加载后保存。",
    "重新加载",
    "资料已保存",
    "请输入显示名称。",
    "前往控制面板",
  ],
};
export function accountCopy(language: string): Copy {
  const values = translations[language.split("-")[0]] ?? translations.en;
  return Object.fromEntries(keys.map((key, i) => [key, values[i]])) as Copy;
}
