const translations: Record<string, string[]> = {
  en: [
    "Username",
    "That handle is taken.",
    "3–20 characters: letters, numbers, _ or -.",
    "Current",
    "No username — others see",
    "Connect a wallet.",
    "Saving…",
    "Update",
    "Claim",
    "Username saved",
    "Could not save username.",
  ],
  es: [
    "Nombre de usuario",
    "Ese nombre ya está en uso.",
    "3–20 caracteres: letras, números, _ o -.",
    "Actual",
    "Sin nombre de usuario; otros ven",
    "Conecta una billetera.",
    "Guardando…",
    "Actualizar",
    "Reservar",
    "Nombre de usuario guardado",
    "No se pudo guardar el nombre de usuario.",
  ],
  fr: [
    "Nom d’utilisateur",
    "Ce nom est déjà utilisé.",
    "3 à 20 caractères : lettres, chiffres, _ ou -.",
    "Actuel",
    "Sans nom d’utilisateur ; les autres voient",
    "Connectez un portefeuille.",
    "Enregistrement…",
    "Mettre à jour",
    "Réserver",
    "Nom d’utilisateur enregistré",
    "Impossible d’enregistrer le nom d’utilisateur.",
  ],
  pt: [
    "Nome de usuário",
    "Esse nome já está em uso.",
    "3–20 caracteres: letras, números, _ ou -.",
    "Atual",
    "Sem nome de usuário; outros veem",
    "Conecte uma carteira.",
    "Salvando…",
    "Atualizar",
    "Reservar",
    "Nome de usuário salvo",
    "Não foi possível salvar o nome de usuário.",
  ],
  it: [
    "Nome utente",
    "Questo nome è già in uso.",
    "3–20 caratteri: lettere, numeri, _ o -.",
    "Attuale",
    "Senza nome utente; gli altri vedono",
    "Collega un portafoglio.",
    "Salvataggio…",
    "Aggiorna",
    "Prenota",
    "Nome utente salvato",
    "Impossibile salvare il nome utente.",
  ],
  ja: [
    "ユーザー名",
    "この名前は使用されています。",
    "3～20文字：英数字、_ または -。",
    "現在",
    "ユーザー名なし。他の人には次が表示されます",
    "ウォレットを接続してください。",
    "保存中…",
    "更新",
    "取得",
    "ユーザー名を保存しました",
    "ユーザー名を保存できませんでした。",
  ],
  ko: [
    "사용자 이름",
    "이미 사용 중인 이름입니다.",
    "3–20자: 영문자, 숫자, _ 또는 -.",
    "현재",
    "사용자 이름이 없어 다른 사람에게 표시되는 값",
    "지갑을 연결하세요.",
    "저장 중…",
    "업데이트",
    "등록",
    "사용자 이름 저장됨",
    "사용자 이름을 저장하지 못했습니다.",
  ],
  zh: [
    "用户名",
    "该用户名已被使用。",
    "3–20 个字符：字母、数字、_ 或 -。",
    "当前",
    "未设置用户名，其他人将看到",
    "请连接钱包。",
    "保存中…",
    "更新",
    "注册",
    "用户名已保存",
    "无法保存用户名。",
  ],
};
export function usernameCopy(language: string) {
  const [
    label,
    taken,
    invalid,
    current,
    unnamed,
    connect,
    saving,
    update,
    claim,
    saved,
    error,
  ] = translations[language.split("-")[0]] ?? translations.en;
  return {
    label,
    taken,
    invalid,
    current,
    unnamed,
    connect,
    saving,
    update,
    claim,
    saved,
    error,
  };
}
