"use client";

import { useTranslation } from "react-i18next";

type PublicDeckLanguage = "en" | "es" | "fr" | "pt" | "ja" | "ko";

type Pair = [string, string];
type Triple = [string, string, string];

export type DeckCopy = {
  nav: { deck: string; present: string; slides: string; hint: string; next: string; previous: string; exit: string; investorOverview: string };
  hero: { eyebrow: string; title: string; accent: string; copy: string };
  problem: { section: string; kicker: string; title: string; accent: string; intro: string; items: Pair[]; insight: string };
  thesis: { section: string; kicker: string; title: string; accent: string; copy: string; center: string; rails: string[] };
  loop: { section: string; kicker: string; title: string; accent: string; steps: Pair[]; cycle: string; principles: Pair[] };
  surfaces: { section: string; kicker: string; title: string; accent: string; items: { label: string; title: string; copy: string; foot: string }[]; summary: string };
  live: { section: string; kicker: string; title: string; accent: string; badge: string; intro: string; items: Pair[]; note: string };
  proof: { section: string; kicker: string; title: string; accent: string; team: string; connected: string; roles: string[]; model: string; items: Pair[] };
  business: { section: string; kicker: string; title: string; accent: string; intro: string; phases: Triple[]; revenues: string[] };
  gtm: { section: string; kicker: string; title: string; accent: string; wedgeTitle: string; wedge: string; grow: string; stages: Pair[] };
  moat: { section: string; kicker: string; title: string; accent: string; intro: string; layers: Pair[]; flywheel: string; compound: string; layer: string };
  roadmap: { section: string; kicker: string; title: string; accent: string; badge: string; intro: string; focuses: string[]; details: string[][] };
  close: { kicker: string; title: string; accent: string; copy: string; explore: string; partners: string[] };
};

const en: DeckCopy = {
  nav: { deck: "Investor deck", present: "Present", slides: "slides · click any slide to present from there", hint: "Built for a concise investor conversation · no financial amounts", next: "Next slide", previous: "Previous slide", exit: "Exit presentation", investorOverview: "Investor overview" },
  hero: { eyebrow: "AI teams for real business work", title: "From business problem to", accent: "accountable AI team.", copy: "PerkOS discovers where AI can create value, assembles the right team, and provides the operating layer to put that team to work." },
  problem: { section: "The problem", kicker: "The adoption gap", title: "AI adoption has a", accent: "translation gap.", intro: "Models are becoming more capable. Businesses still struggle to turn that capability into reliable work inside their daily operation.", items: [["Find the right problem", "Most businesses know AI matters, but not where it will create measurable value."], ["Translate context", "Generic copilots do not understand the processes, constraints, or knowledge behind the work."], ["Turn answers into action", "A useful response still leaves a person to coordinate tools, people, follow-up, and execution."], ["Trust and measure", "Without ownership, approvals, evidence, and outcomes, AI remains an experiment instead of operations."]], insight: "The bottleneck is no longer access to intelligence. It is turning intelligence into an operating capability." },
  thesis: { section: "Investment thesis", kicker: "Our thesis", title: "The model is not the product.", accent: "The operating system around it is.", copy: "PerkOS is the control plane between business intent and AI execution: context, teams, workflows, approvals, evidence, and infrastructure in one system.", center: "Operating layer", rails: ["Business context", "People + agents", "Control + trust", "Outcomes + evidence"] },
  loop: { section: "The system", kicker: "How PerkOS works", title: "One continuous operating loop,", accent: "not another point solution.", steps: [["Discover", "Understand the business and find the highest-value opportunity."], ["Design", "Turn evidence into a private, structured solution blueprint."], ["Assemble", "Configure the right roles, knowledge, tools, and runtime."], ["Operate", "Coordinate work through projects, tasks, chat, and approvals."], ["Improve", "Use artifacts and outcomes to strengthen the next deployment."]], cycle: "Feeds the next cycle", principles: [["Business-first", "Start with a measurable need, not a model."], ["Human-controlled", "Approvals and boundaries remain explicit."], ["Runtime-agnostic", "Use PerkOS-managed or external AI runtimes."]] },
  surfaces: { section: "Product architecture", kicker: "Product surfaces", title: "Three surfaces.", accent: "One system.", items: [{ label: "01 · DISCOVER", title: "PerkOS Grow", copy: "Adaptive business diagnostics turn unstructured needs into opportunity maps, reports, and a private machine-readable solution artifact.", foot: "Public intake · human-readable report · internal JSON" }, { label: "02 · OPERATE", title: "PerkOS App", copy: "Organizations launch teams, create projects, coordinate tasks, maintain project context, and communicate with every participant.", foot: "Projects · tasks · documents · chat · approvals" }, { label: "03 · CONNECT", title: "PerkOS Infrastructure", copy: "A runtime-neutral foundation connects managed agents and external OpenClaw, Hermes, or custom runtimes without owning their model choices.", foot: "A2A · model gateway · Knowledge · identity · settlement" }], summary: "Each surface is valuable alone. Together they create the discovery-to-operation flywheel." },
  live: { section: "Execution", kicker: "Built and running", title: "What is", accent: "live today.", badge: "Production foundation", intro: "The current platform already spans discovery, operations, runtime connectivity, context, models, and knowledge. The next phase connects these pieces into one repeatable customer journey.", items: [["Adaptive discovery", "Grow interviews, email verification, localized reports, private PDF and JSON artifacts."], ["Project operations", "Organizations, projects, tasks, documents, direct chat, project chat, and team rosters."], ["External runtimes", "Official install and repair flows for OpenClaw and Hermes with two-way PerkOS Chat."], ["Context plane", "Authoritative project, conversation, roster, task, and evidence context before execution."], ["Model gateway", "Multi-provider routing, metering, concurrency control, and bring-your-own-model support."], ["Knowledge layer", "Research requests, evidence metadata, retrieval, and reusable organizational knowledge."]], note: "“Live” describes deployed product capabilities and production acceptance tests. It does not imply commercial revenue or customer volume." },
  proof: { section: "Proof of architecture", kicker: "PerkOS Council", title: "A real heterogeneous team,", accent: "not a staged chatbot demo.", team: "Project team", connected: "Connected", roles: ["OpenClaw · coordinator", "OpenClaw · external", "OpenClaw · external", "Hermes · external", "OpenClaw · external", "OpenClaw · external"], model: "Runtime-owned model routing. PerkOS coordinates work without forcing the agent's model.", items: [["Two-way communication", "Messages travel from Project Chat to each external runtime and replies return visibly to the same conversation."], ["Authoritative context", "Every run receives the current project roster, coordinator, tasks, documents, and conversation scope."], ["Isolation by design", "Tenant, project, conversation, credential, and runtime boundaries prevent context from bleeding between users."]] },
  business: { section: "Business model", kicker: "Commercial engine", title: "Land with a problem.", accent: "Expand with results.", intro: "The customer journey itself becomes the business model: diagnostic entry, solution deployment, recurring operation, and expansion into additional workflows.", phases: [["ENTRY", "Diagnose", "A useful business diagnostic creates trust and identifies the first high-value workflow."], ["LAUNCH", "Deploy", "PerkOS configures the solution, agent roles, integrations, knowledge, and controls."], ["RECURRING", "Operate", "The customer returns to projects, work, approvals, reporting, and ongoing AI usage."], ["EXPANSION", "Compound", "New workflows, templates, partners, and agent services expand the relationship."]], revenues: ["Solution design and implementation", "Platform, runtime, and model usage", "Partner distribution and agent services"] },
  gtm: { section: "Go to market", kicker: "Focused distribution", title: "Start where the pain is specific.", accent: "Scale what repeats.", wedgeTitle: "Our wedge is not “AI for everyone.”", wedge: "It is a concrete workflow for a real business, with a clear owner, measurable friction, and a path from diagnosis to deployment.", grow: "Grow is both the front door and the learning system for this motion.", stages: [["Design partners", "Work closely with businesses where operational pain is visible, frequent, and expensive in time."], ["Vertical playbooks", "Turn repeated discoveries into reusable solution blueprints for clinics, agencies, local services, and commerce."], ["Channel partners", "Enable consultants, operators, and software partners to bring qualified businesses into the PerkOS workflow."], ["Template flywheel", "Every successful deployment improves the private catalog, shortening time-to-value for the next business."]] },
  moat: { section: "Defensibility", kicker: "The compounding advantage", title: "The moat is the", accent: "closed loop.", intro: "Point tools can copy a feature. PerkOS compounds across discovery, solution design, execution context, runtime interoperability, and verifiable operations.", layers: [["Discovery data", "Structured evidence about what businesses actually need."], ["Solution blueprints", "Reusable private patterns that map needs to roles and workflows."], ["Context plane", "Current project truth delivered safely to every participating runtime."], ["Runtime network", "Managed and external agents connected without model lock-in."], ["Trust rails", "Identity, authorization, usage, receipts, and optional settlement."]], flywheel: "More deployments → better blueprints → faster outcomes → stronger distribution.", compound: "Compounding system", layer: "LAYER" },
  roadmap: { section: "Roadmap", kicker: "Where we are going", title: "The next", accent: "twelve months.", badge: "Forward plan", intro: "The roadmap moves from connecting today's products to making successful solutions repeatable, scalable, and increasingly self-improving.", focuses: ["Close the discovery-to-deployment loop", "Make solutions repeatable", "Scale the operating layer", "Compound into a network"], details: [["Native Grow workflow inside PerkOS", "Private blueprint and reviewer path", "Unified onboarding and observability"], ["Vertical solution templates", "Outcome measurement loop", "Design-partner deployment playbook"], ["Multi-tenant orchestration at scale", "Private solution catalog", "Usage, billing, and partner controls"], ["Self-improving solution network", "Cross-organization agent services", "Optional machine-to-machine commerce"]] },
  close: { kicker: "The vision", title: "Every business should be able to operate with an", accent: "AI team.", copy: "PerkOS is building the system that turns business intent into accountable AI work — from the first question to the operating team.", explore: "Explore PerkOS", partners: ["Design partners", "Ecosystem partners", "Investors"] },
};

const es: DeckCopy = {
  nav: { deck: "Deck para inversionistas", present: "Presentar", slides: "láminas · haz clic en una para presentar desde allí", hint: "Diseñado para una conversación seria y concisa · sin montos financieros", next: "Siguiente lámina", previous: "Lámina anterior", exit: "Salir de la presentación", investorOverview: "Presentación para inversionistas" },
  hero: { eyebrow: "Equipos de IA para trabajo real", title: "De un problema de negocio a un", accent: "equipo de IA responsable.", copy: "PerkOS descubre dónde la IA puede crear valor, arma el equipo correcto y aporta la capa operativa para ponerlo a trabajar." },
  problem: { section: "El problema", kicker: "La brecha de adopción", title: "La adopción de IA tiene una", accent: "brecha de traducción.", intro: "Los modelos son cada vez más capaces. Las empresas aún no logran convertir esa capacidad en trabajo confiable dentro de su operación diaria.", items: [["Encontrar el problema correcto", "La mayoría sabe que la IA importa, pero no dónde producirá valor medible."], ["Traducir el contexto", "Los copilotos genéricos no entienden los procesos, límites ni conocimiento detrás del trabajo."], ["Convertir respuestas en acción", "Una buena respuesta todavía deja a una persona coordinando herramientas, seguimiento y ejecución."], ["Confiar y medir", "Sin responsables, aprobaciones, evidencia y resultados, la IA sigue siendo un experimento."]], insight: "El cuello de botella ya no es acceder a inteligencia. Es convertirla en una capacidad operativa." },
  thesis: { section: "Tesis de inversión", kicker: "Nuestra tesis", title: "El modelo no es el producto.", accent: "El sistema operativo a su alrededor sí.", copy: "PerkOS es el plano de control entre la intención del negocio y la ejecución de IA: contexto, equipos, flujos, aprobaciones, evidencia e infraestructura en un solo sistema.", center: "Capa operativa", rails: ["Contexto del negocio", "Personas + agentes", "Control + confianza", "Resultados + evidencia"] },
  loop: { section: "El sistema", kicker: "Cómo funciona PerkOS", title: "Un ciclo operativo continuo,", accent: "no otra solución aislada.", steps: [["Descubrir", "Entender el negocio y encontrar la oportunidad de mayor valor."], ["Diseñar", "Convertir la evidencia en un blueprint privado y estructurado."], ["Armar", "Configurar roles, conocimiento, herramientas y runtime."], ["Operar", "Coordinar proyectos, tareas, chat y aprobaciones."], ["Mejorar", "Usar artefactos y resultados para fortalecer el siguiente despliegue."]], cycle: "Alimenta el siguiente ciclo", principles: [["Primero el negocio", "Partir de una necesidad medible, no de un modelo."], ["Control humano", "Aprobaciones y límites siempre explícitos."], ["Independiente del runtime", "Usar IA administrada por PerkOS o runtimes externos."]] },
  surfaces: { section: "Arquitectura de producto", kicker: "Superficies del producto", title: "Tres superficies.", accent: "Un solo sistema.", items: [{ label: "01 · DESCUBRIR", title: "PerkOS Grow", copy: "Diagnósticos adaptativos convierten necesidades dispersas en mapas de oportunidades, reportes y un artefacto privado legible por máquinas.", foot: "Captura pública · reporte humano · JSON interno" }, { label: "02 · OPERAR", title: "PerkOS App", copy: "Las organizaciones lanzan equipos, crean proyectos, coordinan tareas, conservan contexto y se comunican con cada participante.", foot: "Proyectos · tareas · documentos · chat · aprobaciones" }, { label: "03 · CONECTAR", title: "Infraestructura PerkOS", copy: "Una base neutral conecta agentes administrados y runtimes externos OpenClaw, Hermes o custom sin imponerles un modelo.", foot: "A2A · gateway de modelos · Knowledge · identidad · liquidación" }], summary: "Cada superficie tiene valor por sí sola. Juntas crean el ciclo de descubrimiento a operación." },
  live: { section: "Ejecución", kicker: "Construido y operando", title: "Lo que está", accent: "activo hoy.", badge: "Base en producción", intro: "La plataforma ya cubre descubrimiento, operaciones, conectividad de runtimes, contexto, modelos y conocimiento. La siguiente fase los une en un recorrido repetible para el cliente.", items: [["Descubrimiento adaptativo", "Entrevistas Grow, verificación de email, reportes localizados y artefactos privados PDF y JSON."], ["Operación de proyectos", "Organizaciones, proyectos, tareas, documentos, chat directo, chat de proyecto y equipos."], ["Runtimes externos", "Flujos oficiales de instalación y reparación para OpenClaw y Hermes con chat bidireccional."], ["Plano de contexto", "Contexto autoritativo de proyecto, conversación, equipo, tareas y evidencia antes de ejecutar."], ["Gateway de modelos", "Routing multiproveedor, medición, control de concurrencia y modelos propios."], ["Capa de conocimiento", "Solicitudes de research, evidencia, recuperación y conocimiento organizacional reutilizable."]], note: "“Activo” describe capacidades desplegadas y pruebas de aceptación en producción. No implica ingresos ni volumen de clientes." },
  proof: { section: "Prueba de arquitectura", kicker: "PerkOS Council", title: "Un equipo heterogéneo real,", accent: "no una demo preparada.", team: "Equipo del proyecto", connected: "Conectado", roles: ["OpenClaw · coordinador", "OpenClaw · externo", "OpenClaw · externo", "Hermes · externo", "OpenClaw · externo", "OpenClaw · externo"], model: "El runtime controla su modelo. PerkOS coordina el trabajo sin imponer el modelo del agente.", items: [["Comunicación bidireccional", "Los mensajes viajan del Chat del proyecto al runtime externo y las respuestas vuelven a la misma conversación."], ["Contexto autoritativo", "Cada ejecución recibe equipo, coordinador, tareas, documentos y alcance de conversación vigentes."], ["Aislamiento por diseño", "Los límites de tenant, proyecto, conversación, credencial y runtime evitan mezclar usuarios."]] },
  business: { section: "Modelo de negocio", kicker: "Motor comercial", title: "Entrar con un problema.", accent: "Crecer con resultados.", intro: "El recorrido del cliente se convierte en el modelo: diagnóstico, despliegue de solución, operación recurrente y expansión a nuevos flujos.", phases: [["ENTRADA", "Diagnosticar", "Un diagnóstico útil crea confianza e identifica el primer flujo de alto valor."], ["LANZAMIENTO", "Desplegar", "PerkOS configura solución, roles, integraciones, conocimiento y controles."], ["RECURRENCIA", "Operar", "El cliente vuelve a proyectos, trabajo, aprobaciones, reportes y uso continuo de IA."], ["EXPANSIÓN", "Multiplicar", "Nuevos flujos, plantillas, socios y servicios de agentes amplían la relación."]], revenues: ["Diseño e implementación de soluciones", "Uso de plataforma, runtime y modelos", "Distribución de socios y servicios de agentes"] },
  gtm: { section: "Salida al mercado", kicker: "Distribución enfocada", title: "Empezar donde el dolor es específico.", accent: "Escalar lo que se repite.", wedgeTitle: "Nuestra entrada no es “IA para todos”.", wedge: "Es un flujo concreto para un negocio real, con responsable claro, fricción medible y camino del diagnóstico al despliegue.", grow: "Grow es la puerta de entrada y el sistema de aprendizaje de esta estrategia.", stages: [["Socios de diseño", "Trabajar con negocios cuyo dolor operativo es visible, frecuente y costoso en tiempo."], ["Playbooks verticales", "Convertir hallazgos repetidos en blueprints para clínicas, agencias, servicios y comercio."], ["Socios de canal", "Permitir que consultores, operadores y software lleven negocios calificados a PerkOS."], ["Ciclo de plantillas", "Cada despliegue exitoso mejora el catálogo privado y reduce el tiempo a valor."]] },
  moat: { section: "Defensibilidad", kicker: "La ventaja acumulativa", title: "El moat es el", accent: "ciclo cerrado.", intro: "Una herramienta puntual puede copiar una función. PerkOS acumula ventaja en descubrimiento, diseño, contexto de ejecución, interoperabilidad y operación verificable.", layers: [["Datos de descubrimiento", "Evidencia estructurada de lo que los negocios realmente necesitan."], ["Blueprints de solución", "Patrones privados reutilizables que conectan necesidades, roles y flujos."], ["Plano de contexto", "La verdad vigente del proyecto llega de forma segura a cada runtime."], ["Red de runtimes", "Agentes administrados y externos sin dependencia de un modelo."], ["Rieles de confianza", "Identidad, autorización, uso, recibos y liquidación opcional."]], flywheel: "Más despliegues → mejores blueprints → resultados más rápidos → mayor distribución.", compound: "Sistema acumulativo", layer: "CAPA" },
  roadmap: { section: "Roadmap", kicker: "Hacia dónde vamos", title: "Los próximos", accent: "doce meses.", badge: "Plan de avance", intro: "El roadmap conecta los productos actuales y convierte soluciones exitosas en capacidades repetibles, escalables y cada vez más autónomas.", focuses: ["Cerrar el ciclo de descubrimiento a despliegue", "Volver repetibles las soluciones", "Escalar la capa operativa", "Convertirse en una red"], details: [["Grow nativo dentro de PerkOS", "Blueprint privado y revisión humana", "Onboarding y observabilidad unificados"], ["Plantillas verticales de solución", "Ciclo de medición de resultados", "Playbook para socios de diseño"], ["Orquestación multi-tenant a escala", "Catálogo privado de soluciones", "Uso, facturación y controles de socios"], ["Red de soluciones que aprende", "Servicios entre organizaciones", "Comercio opcional máquina a máquina"]] },
  close: { kicker: "La visión", title: "Toda empresa debería poder operar con un", accent: "equipo de IA.", copy: "PerkOS construye el sistema que convierte intención de negocio en trabajo de IA responsable: desde la primera pregunta hasta el equipo operativo.", explore: "Conocer PerkOS", partners: ["Socios de diseño", "Socios de ecosistema", "Inversionistas"] },
};

const fr: DeckCopy = {
  ...en,
  nav: { deck: "Deck investisseurs", present: "Présenter", slides: "diapositives · cliquez pour démarrer à cet endroit", hint: "Conçu pour un échange investisseur concis · sans montants financiers", next: "Diapositive suivante", previous: "Diapositive précédente", exit: "Quitter la présentation", investorOverview: "Présentation investisseurs" },
  hero: { eyebrow: "Des équipes IA pour le travail réel", title: "Du problème métier à une", accent: "équipe IA responsable.", copy: "PerkOS identifie où l’IA crée de la valeur, assemble la bonne équipe et fournit la couche opérationnelle qui la met au travail." },
  problem: { ...en.problem, section: "Le problème", kicker: "Le fossé d’adoption", title: "L’adoption de l’IA souffre d’un", accent: "fossé de traduction.", intro: "Les modèles progressent. Les entreprises peinent encore à transformer leurs capacités en travail fiable dans leurs opérations quotidiennes.", items: [["Trouver le bon problème", "Les entreprises savent que l’IA compte, mais pas où elle créera une valeur mesurable."], ["Traduire le contexte", "Les copilotes génériques ignorent les processus, contraintes et connaissances du travail."], ["Transformer les réponses en action", "Une bonne réponse laisse encore une personne coordonner outils, suivi et exécution."], ["Faire confiance et mesurer", "Sans responsables, validations, preuves et résultats, l’IA reste une expérience."]], insight: "Le frein n’est plus l’accès à l’intelligence, mais sa transformation en capacité opérationnelle." },
  thesis: { ...en.thesis, section: "Thèse d’investissement", kicker: "Notre thèse", title: "Le modèle n’est pas le produit.", accent: "Le système d’exploitation autour de lui l’est.", copy: "PerkOS est le plan de contrôle entre l’intention métier et l’exécution IA : contexte, équipes, workflows, validations, preuves et infrastructure réunis.", center: "Couche opérationnelle", rails: ["Contexte métier", "Humains + agents", "Contrôle + confiance", "Résultats + preuves"] },
  loop: { ...en.loop, section: "Le système", kicker: "Comment fonctionne PerkOS", title: "Une boucle opérationnelle continue,", accent: "pas un outil isolé.", steps: [["Découvrir", "Comprendre l’entreprise et repérer l’opportunité prioritaire."], ["Concevoir", "Transformer les preuves en blueprint privé et structuré."], ["Assembler", "Configurer les rôles, connaissances, outils et runtime."], ["Opérer", "Coordonner projets, tâches, chat et validations."], ["Améliorer", "Utiliser les résultats pour renforcer le prochain déploiement."]], cycle: "Alimente le cycle suivant", principles: [["Métier d’abord", "Partir d’un besoin mesurable, pas d’un modèle."], ["Contrôle humain", "Validations et limites restent explicites."], ["Agnostique au runtime", "Utiliser l’IA PerkOS ou des runtimes externes."]] },
  surfaces: { ...en.surfaces, section: "Architecture produit", kicker: "Surfaces produit", title: "Trois surfaces.", accent: "Un seul système.", items: [{ label: "01 · DÉCOUVRIR", title: "PerkOS Grow", copy: "Des diagnostics adaptatifs transforment les besoins en cartes d’opportunités, rapports et artefact privé lisible par machine.", foot: "Collecte publique · rapport humain · JSON interne" }, { label: "02 · OPÉRER", title: "PerkOS App", copy: "Les organisations lancent des équipes, créent des projets, coordonnent les tâches, gardent le contexte et communiquent.", foot: "Projets · tâches · documents · chat · validations" }, { label: "03 · CONNECTER", title: "Infrastructure PerkOS", copy: "Une base neutre connecte agents gérés et runtimes OpenClaw, Hermes ou custom sans imposer leur modèle.", foot: "A2A · passerelle modèles · Knowledge · identité · règlement" }], summary: "Chaque surface vaut seule. Ensemble, elles créent la boucle découverte-opération." },
  live: { ...en.live, section: "Exécution", kicker: "Construit et opérationnel", title: "Ce qui est", accent: "déjà en production.", badge: "Socle en production", intro: "La plateforme couvre déjà découverte, opérations, runtimes, contexte, modèles et connaissances. La phase suivante les relie en un parcours client reproductible.", items: [["Découverte adaptative", "Entretiens Grow, vérification email, rapports localisés, PDF et JSON privés."], ["Opérations de projet", "Organisations, projets, tâches, documents, chats directs et projet, équipes."], ["Runtimes externes", "Installation et réparation officielles pour OpenClaw et Hermes avec chat bidirectionnel."], ["Plan de contexte", "Contexte fiable du projet, de la conversation, de l’équipe, des tâches et des preuves."], ["Passerelle de modèles", "Routage multi-fournisseurs, mesure, concurrence et modèles apportés par le client."], ["Couche Knowledge", "Demandes de recherche, preuves, recherche et connaissances réutilisables."]], note: "« En production » décrit des capacités déployées et testées. Cela ne suppose ni revenus ni volume client." },
  proof: { ...en.proof, section: "Preuve d’architecture", kicker: "PerkOS Council", title: "Une équipe hétérogène réelle,", accent: "pas une démo scénarisée.", team: "Équipe projet", connected: "Connecté", roles: ["OpenClaw · coordinateur", "OpenClaw · externe", "OpenClaw · externe", "Hermes · externe", "OpenClaw · externe", "OpenClaw · externe"], model: "Le runtime choisit son modèle. PerkOS coordonne sans imposer le modèle de l’agent.", items: [["Communication bidirectionnelle", "Les messages partent du chat projet vers le runtime externe et reviennent dans la même conversation."], ["Contexte de référence", "Chaque exécution reçoit l’équipe, le coordinateur, les tâches, documents et la portée à jour."], ["Isolation par conception", "Les limites tenant, projet, conversation, identifiant et runtime empêchent tout mélange."]] },
  business: { ...en.business, section: "Modèle économique", kicker: "Moteur commercial", title: "Entrer par un problème.", accent: "Grandir par les résultats.", intro: "Le parcours client devient le modèle : diagnostic, déploiement, opération récurrente et extension à d’autres workflows.", phases: [["ENTRÉE", "Diagnostiquer", "Un diagnostic utile crée la confiance et trouve le premier workflow à forte valeur."], ["LANCEMENT", "Déployer", "PerkOS configure solution, rôles, intégrations, connaissances et contrôles."], ["RÉCURRENCE", "Opérer", "Le client revient aux projets, validations, rapports et usages IA continus."], ["EXPANSION", "Composer", "Nouveaux workflows, modèles, partenaires et services étendent la relation."]], revenues: ["Conception et mise en œuvre", "Usage plateforme, runtime et modèles", "Distribution partenaires et services d’agents"] },
  gtm: { ...en.gtm, section: "Mise sur le marché", kicker: "Distribution ciblée", title: "Commencer là où la douleur est précise.", accent: "Industrialiser ce qui se répète.", wedgeTitle: "Notre point d’entrée n’est pas « l’IA pour tous ».", wedge: "C’est un workflow concret pour une entreprise réelle, avec un responsable, une friction mesurable et un chemin du diagnostic au déploiement.", grow: "Grow est à la fois la porte d’entrée et le système d’apprentissage de cette stratégie.", stages: [["Partenaires de conception", "Travailler avec les entreprises dont la douleur opérationnelle est visible et fréquente."], ["Playbooks verticaux", "Transformer les découvertes répétées en blueprints pour cliniques, agences, services et commerce."], ["Partenaires de distribution", "Permettre aux consultants et logiciels d’amener des entreprises qualifiées vers PerkOS."], ["Boucle de templates", "Chaque déploiement réussi améliore le catalogue privé et accélère la valeur suivante."]] },
  moat: { ...en.moat, section: "Défensibilité", kicker: "L’avantage cumulatif", title: "Le moat est la", accent: "boucle fermée.", intro: "Un outil ponctuel peut copier une fonction. PerkOS cumule découverte, conception, contexte, interopérabilité et opérations vérifiables.", layers: [["Données de découverte", "Preuves structurées de ce dont les entreprises ont vraiment besoin."], ["Blueprints de solution", "Modèles privés réutilisables reliant besoins, rôles et workflows."], ["Plan de contexte", "La vérité actuelle du projet est transmise à chaque runtime."], ["Réseau de runtimes", "Agents gérés et externes sans verrouillage de modèle."], ["Rails de confiance", "Identité, autorisation, usage, reçus et règlement optionnel."]], flywheel: "Plus de déploiements → meilleurs blueprints → résultats plus rapides → meilleure distribution.", compound: "Système cumulatif", layer: "COUCHE" },
  roadmap: { ...en.roadmap, section: "Feuille de route", kicker: "Notre trajectoire", title: "Les douze", accent: "prochains mois.", badge: "Plan prospectif", intro: "La feuille de route relie les produits actuels et rend les solutions réussies reproductibles, évolutives et de plus en plus autonomes.", focuses: ["Boucler découverte et déploiement", "Rendre les solutions reproductibles", "Faire évoluer la couche opérationnelle", "Composer un réseau"], details: [["Grow natif dans PerkOS", "Blueprint privé et revue humaine", "Onboarding et observabilité unifiés"], ["Templates de solutions verticales", "Boucle de mesure des résultats", "Playbook partenaires de conception"], ["Orchestration multi-tenant à l’échelle", "Catalogue privé de solutions", "Usage, facturation et contrôle partenaires"], ["Réseau de solutions apprenant", "Services inter-organisations", "Commerce machine-à-machine optionnel"]] },
  close: { ...en.close, kicker: "La vision", title: "Chaque entreprise devrait pouvoir opérer avec une", accent: "équipe IA.", copy: "PerkOS construit le système qui transforme l’intention métier en travail IA responsable, de la première question à l’équipe opérationnelle.", explore: "Découvrir PerkOS", partners: ["Partenaires de conception", "Partenaires écosystème", "Investisseurs"] },
};

const pt: DeckCopy = {
  ...es,
  nav: { deck: "Deck para investidores", present: "Apresentar", slides: "slides · clique para apresentar a partir dali", hint: "Criado para uma conversa séria e concisa · sem valores financeiros", next: "Próximo slide", previous: "Slide anterior", exit: "Sair da apresentação", investorOverview: "Apresentação para investidores" },
  hero: { eyebrow: "Equipes de IA para trabalho real", title: "Do problema de negócio a uma", accent: "equipe de IA responsável.", copy: "A PerkOS descobre onde a IA pode gerar valor, monta a equipe certa e oferece a camada operacional para colocá-la para trabalhar." },
  problem: { ...es.problem, section: "O problema", kicker: "A lacuna de adoção", title: "A adoção de IA tem uma", accent: "lacuna de tradução.", intro: "Os modelos estão mais capazes. As empresas ainda têm dificuldade em transformar essa capacidade em trabalho confiável na operação diária.", items: [["Encontrar o problema certo", "As empresas sabem que a IA importa, mas não onde ela criará valor mensurável."], ["Traduzir o contexto", "Copilotos genéricos não entendem processos, restrições e conhecimento do trabalho."], ["Transformar respostas em ação", "Uma boa resposta ainda deixa alguém coordenando ferramentas, acompanhamento e execução."], ["Confiar e medir", "Sem responsáveis, aprovações, evidências e resultados, a IA continua sendo um experimento."]], insight: "O gargalo não é mais acessar inteligência. É transformá-la em capacidade operacional." },
  thesis: { ...es.thesis, section: "Tese de investimento", kicker: "Nossa tese", title: "O modelo não é o produto.", accent: "O sistema operacional ao redor dele é.", copy: "A PerkOS é o plano de controle entre a intenção do negócio e a execução de IA: contexto, equipes, fluxos, aprovações, evidências e infraestrutura.", center: "Camada operacional", rails: ["Contexto do negócio", "Pessoas + agentes", "Controle + confiança", "Resultados + evidências"] },
  loop: { ...es.loop, section: "O sistema", kicker: "Como a PerkOS funciona", title: "Um ciclo operacional contínuo,", accent: "não outra solução isolada.", steps: [["Descobrir", "Entender o negócio e encontrar a oportunidade de maior valor."], ["Projetar", "Transformar evidências em um blueprint privado e estruturado."], ["Montar", "Configurar funções, conhecimento, ferramentas e runtime."], ["Operar", "Coordenar projetos, tarefas, chat e aprovações."], ["Melhorar", "Usar resultados para fortalecer a próxima implantação."]], cycle: "Alimenta o próximo ciclo", principles: [["Negócio primeiro", "Começar com uma necessidade mensurável, não um modelo."], ["Controle humano", "Aprovações e limites permanecem explícitos."], ["Agnóstico ao runtime", "Usar IA PerkOS ou runtimes externos."]] },
  surfaces: { ...es.surfaces, section: "Arquitetura do produto", kicker: "Superfícies do produto", title: "Três superfícies.", accent: "Um só sistema.", items: [{ label: "01 · DESCOBRIR", title: "PerkOS Grow", copy: "Diagnósticos adaptativos transformam necessidades em mapas de oportunidades, relatórios e um artefato privado legível por máquina.", foot: "Entrada pública · relatório humano · JSON interno" }, { label: "02 · OPERAR", title: "PerkOS App", copy: "Organizações lançam equipes, criam projetos, coordenam tarefas, mantêm contexto e conversam com cada participante.", foot: "Projetos · tarefas · documentos · chat · aprovações" }, { label: "03 · CONECTAR", title: "Infraestrutura PerkOS", copy: "Uma base neutra conecta agentes gerenciados e runtimes OpenClaw, Hermes ou custom sem impor um modelo.", foot: "A2A · gateway de modelos · Knowledge · identidade · liquidação" }], summary: "Cada superfície tem valor sozinha. Juntas, criam o ciclo da descoberta à operação." },
  live: { ...es.live, section: "Execução", kicker: "Construído e operando", title: "O que está", accent: "ativo hoje.", badge: "Base em produção", intro: "A plataforma já cobre descoberta, operações, runtimes, contexto, modelos e conhecimento. A próxima fase une tudo em uma jornada repetível.", items: [["Descoberta adaptativa", "Entrevistas Grow, verificação de email, relatórios localizados, PDF e JSON privados."], ["Operações de projeto", "Organizações, projetos, tarefas, documentos, chats e equipes."], ["Runtimes externos", "Instalação e reparo oficiais para OpenClaw e Hermes com chat bidirecional."], ["Plano de contexto", "Contexto confiável de projeto, conversa, equipe, tarefas e evidências."], ["Gateway de modelos", "Roteamento multi-provedor, medição, concorrência e modelos próprios."], ["Camada de conhecimento", "Pesquisa, evidências, recuperação e conhecimento reutilizável."]], note: "“Ativo” descreve capacidades implantadas e testadas em produção. Não implica receita ou volume de clientes." },
  proof: { ...es.proof, section: "Prova de arquitetura", kicker: "PerkOS Council", title: "Uma equipe heterogênea real,", accent: "não uma demo ensaiada.", team: "Equipe do projeto", connected: "Conectado", roles: ["OpenClaw · coordenador", "OpenClaw · externo", "OpenClaw · externo", "Hermes · externo", "OpenClaw · externo", "OpenClaw · externo"], model: "O runtime controla o modelo. A PerkOS coordena sem impor o modelo do agente.", items: [["Comunicação bidirecional", "Mensagens vão do chat do projeto ao runtime externo e retornam à mesma conversa."], ["Contexto de referência", "Cada execução recebe equipe, coordenador, tarefas, documentos e escopo atuais."], ["Isolamento por design", "Limites de tenant, projeto, conversa, credencial e runtime evitam mistura entre usuários."]] },
  business: { ...es.business, section: "Modelo de negócio", kicker: "Motor comercial", title: "Entrar com um problema.", accent: "Expandir com resultados.", intro: "A jornada do cliente vira o modelo: diagnóstico, implantação, operação recorrente e expansão para novos fluxos.", phases: [["ENTRADA", "Diagnosticar", "Um diagnóstico útil cria confiança e identifica o primeiro fluxo de alto valor."], ["LANÇAMENTO", "Implantar", "A PerkOS configura solução, funções, integrações, conhecimento e controles."], ["RECORRÊNCIA", "Operar", "O cliente volta a projetos, aprovações, relatórios e uso contínuo de IA."], ["EXPANSÃO", "Compor", "Novos fluxos, modelos, parceiros e serviços ampliam a relação."]], revenues: ["Desenho e implantação de soluções", "Uso da plataforma, runtime e modelos", "Distribuição de parceiros e serviços de agentes"] },
  gtm: { ...es.gtm, section: "Estratégia de mercado", kicker: "Distribuição focada", title: "Começar onde a dor é específica.", accent: "Escalar o que se repete.", wedgeTitle: "Nossa entrada não é “IA para todos”.", wedge: "É um fluxo concreto para um negócio real, com responsável claro, fricção mensurável e caminho do diagnóstico à implantação.", grow: "Grow é a porta de entrada e o sistema de aprendizagem dessa estratégia.", stages: [["Parceiros de design", "Trabalhar com negócios cuja dor operacional é visível, frequente e cara em tempo."], ["Playbooks verticais", "Transformar descobertas repetidas em blueprints para clínicas, agências, serviços e comércio."], ["Parceiros de canal", "Permitir que consultores e softwares levem negócios qualificados à PerkOS."], ["Ciclo de templates", "Cada implantação bem-sucedida melhora o catálogo privado e acelera o valor seguinte."]] },
  moat: { ...es.moat, section: "Defensibilidade", kicker: "A vantagem cumulativa", title: "O moat é o", accent: "ciclo fechado.", intro: "Uma ferramenta pontual pode copiar uma função. A PerkOS acumula descoberta, design, contexto, interoperabilidade e operações verificáveis.", layers: [["Dados de descoberta", "Evidência estruturada do que os negócios realmente precisam."], ["Blueprints de solução", "Padrões privados reutilizáveis que ligam necessidades, funções e fluxos."], ["Plano de contexto", "A verdade atual do projeto chega com segurança a cada runtime."], ["Rede de runtimes", "Agentes gerenciados e externos sem dependência de modelo."], ["Trilhos de confiança", "Identidade, autorização, uso, recibos e liquidação opcional."]], flywheel: "Mais implantações → melhores blueprints → resultados mais rápidos → maior distribuição.", compound: "Sistema cumulativo", layer: "CAMADA" },
  roadmap: { ...es.roadmap, section: "Roadmap", kicker: "Para onde vamos", title: "Os próximos", accent: "doze meses.", badge: "Plano futuro", intro: "O roadmap conecta os produtos atuais e torna soluções bem-sucedidas repetíveis, escaláveis e cada vez mais autônomas.", focuses: ["Fechar o ciclo da descoberta à implantação", "Tornar soluções repetíveis", "Escalar a camada operacional", "Compor uma rede"], details: [["Grow nativo dentro da PerkOS", "Blueprint privado e revisão humana", "Onboarding e observabilidade unificados"], ["Templates verticais de solução", "Ciclo de medição de resultados", "Playbook de parceiros de design"], ["Orquestração multi-tenant em escala", "Catálogo privado de soluções", "Uso, faturamento e controles de parceiros"], ["Rede de soluções que aprende", "Serviços entre organizações", "Comércio máquina a máquina opcional"]] },
  close: { ...es.close, kicker: "A visão", title: "Toda empresa deveria poder operar com uma", accent: "equipe de IA.", copy: "A PerkOS constrói o sistema que transforma intenção de negócio em trabalho de IA responsável, da primeira pergunta à equipe operacional.", explore: "Conhecer a PerkOS", partners: ["Parceiros de design", "Parceiros de ecossistema", "Investidores"] },
};

const ja: DeckCopy = {
  ...en,
  nav: { deck: "投資家向け資料", present: "プレゼン表示", slides: "枚 · 任意のスライドから開始できます", hint: "投資家との簡潔な対話向け · 金額情報なし", next: "次のスライド", previous: "前のスライド", exit: "プレゼンを終了", investorOverview: "投資家向け概要" },
  hero: { eyebrow: "実務を担うAIチーム", title: "事業課題から", accent: "責任あるAIチームへ。", copy: "PerkOSはAIが価値を生む領域を発見し、最適なチームを編成し、実際に働かせる運用基盤を提供します。" },
  problem: { ...en.problem, section: "課題", kicker: "導入のギャップ", title: "AI導入には", accent: "翻訳のギャップがあります。", intro: "モデルは急速に進化しています。それでも企業は、その能力を日々の業務で信頼できる仕事へ変換できていません。", items: [["正しい課題を見つける", "AIが重要だと分かっても、どこで測定可能な価値を生むかは不明です。"], ["文脈を翻訳する", "汎用コパイロットは業務プロセス、制約、知識を理解しません。"], ["回答を行動に変える", "良い回答でも、ツール、フォロー、実行の調整は人に残ります。"], ["信頼し測定する", "責任者、承認、証拠、成果がなければAIは実験のままです。"]], insight: "ボトルネックは知能へのアクセスではなく、知能を運用能力へ変えることです。" },
  thesis: { ...en.thesis, section: "投資テーマ", kicker: "私たちの仮説", title: "モデルそのものは製品ではない。", accent: "周囲のOSこそが製品です。", copy: "PerkOSは事業の意図とAI実行をつなぐコントロールプレーンです。文脈、チーム、ワークフロー、承認、証拠、基盤を一つにします。", center: "運用レイヤー", rails: ["事業コンテキスト", "人 + エージェント", "制御 + 信頼", "成果 + 証拠"] },
  loop: { ...en.loop, section: "システム", kicker: "PerkOSの仕組み", title: "単発ツールではなく、", accent: "連続する運用ループ。", steps: [["発見", "事業を理解し、最も価値の高い機会を見つけます。"], ["設計", "証拠を非公開の構造化ブループリントに変換します。"], ["編成", "役割、知識、ツール、ランタイムを設定します。"], ["運用", "プロジェクト、タスク、チャット、承認を調整します。"], ["改善", "成果を次の導入に反映します。"]], cycle: "次のサイクルへ", principles: [["事業を先に", "モデルではなく測定可能なニーズから始めます。"], ["人が制御", "承認と境界を明確に保ちます。"], ["ランタイム中立", "PerkOS管理または外部AIを利用できます。"]] },
  surfaces: { ...en.surfaces, section: "製品アーキテクチャ", kicker: "製品サーフェス", title: "3つのサーフェス。", accent: "1つのシステム。", items: [{ label: "01 · 発見", title: "PerkOS Grow", copy: "適応型診断がニーズを機会マップ、レポート、機械可読の非公開アーティファクトへ変換します。", foot: "公開入力 · 人向けレポート · 内部JSON" }, { label: "02 · 運用", title: "PerkOS App", copy: "組織がチームを起動し、プロジェクトとタスクを管理し、文脈を保ち、全参加者と連携します。", foot: "プロジェクト · タスク · 文書 · チャット · 承認" }, { label: "03 · 接続", title: "PerkOS Infrastructure", copy: "モデルを強制せず、管理エージェントとOpenClaw、Hermes、カスタムランタイムを接続します。", foot: "A2A · モデルゲートウェイ · Knowledge · ID · 決済" }], summary: "各サーフェス単体でも価値があり、連携すると発見から運用までの循環になります。" },
  live: { ...en.live, section: "実行", kicker: "構築済み・稼働中", title: "現在すでに", accent: "稼働しているもの。", badge: "本番基盤", intro: "現在のプラットフォームは発見、運用、ランタイム接続、文脈、モデル、知識をカバーしています。次はそれらを再現可能な顧客体験へ統合します。", items: [["適応型ディスカバリー", "Grow面談、メール認証、多言語レポート、非公開PDFとJSON。"], ["プロジェクト運用", "組織、プロジェクト、タスク、文書、直接・プロジェクトチャット、チーム。"], ["外部ランタイム", "OpenClawとHermesの公式導入・修復、双方向PerkOS Chat。"], ["コンテキストプレーン", "実行前にプロジェクト、会話、チーム、タスク、証拠の正しい文脈を提供。"], ["モデルゲートウェイ", "複数プロバイダーのルーティング、計測、同時実行制御、BYOM。"], ["Knowledgeレイヤー", "調査依頼、証拠、検索、再利用可能な組織知識。"]], note: "「稼働中」は導入済み機能と本番受入テストを指し、売上や顧客数を意味しません。" },
  proof: { ...en.proof, section: "アーキテクチャ実証", kicker: "PerkOS Council", title: "演出されたチャットではなく、", accent: "実在する異種AIチーム。", team: "プロジェクトチーム", connected: "接続済み", roles: ["OpenClaw · コーディネーター", "OpenClaw · 外部", "OpenClaw · 外部", "Hermes · 外部", "OpenClaw · 外部", "OpenClaw · 外部"], model: "モデル選択はランタイム側が保持。PerkOSはエージェントのモデルを強制せず仕事を調整します。", items: [["双方向通信", "プロジェクトチャットから外部ランタイムへ届き、返信が同じ会話へ戻ります。"], ["正しいコンテキスト", "各実行が最新のチーム、調整役、タスク、文書、会話範囲を受け取ります。"], ["設計段階の分離", "テナント、プロジェクト、会話、認証、ランタイム境界で混在を防ぎます。"]] },
  business: { ...en.business, section: "ビジネスモデル", kicker: "商用エンジン", title: "課題から入り、", accent: "成果で拡大する。", intro: "診断、ソリューション導入、継続運用、追加ワークフローへの拡張という顧客体験そのものがモデルです。", phases: [["入口", "診断", "有用な診断が信頼を築き、最初の高価値ワークフローを見つけます。"], ["導入", "展開", "ソリューション、役割、連携、知識、制御を設定します。"], ["継続", "運用", "顧客はプロジェクト、承認、レポート、継続的なAI利用へ戻ります。"], ["拡大", "蓄積", "新しいフロー、テンプレート、パートナー、エージェントサービスへ広がります。"]], revenues: ["ソリューション設計・導入", "プラットフォーム・ランタイム・モデル利用", "パートナー流通・エージェントサービス"] },
  gtm: { ...en.gtm, section: "市場展開", kicker: "集中した流通", title: "痛みが明確な場所から始め、", accent: "繰り返せるものを拡大。", wedgeTitle: "入口は「すべての人のAI」ではありません。", wedge: "実在する事業の具体的なワークフローで、責任者、測定可能な摩擦、診断から導入までの道筋があります。", grow: "Growはこの戦略の入口であり学習システムです。", stages: [["デザインパートナー", "運用課題が明確で頻繁な企業と密に取り組みます。"], ["業界別プレイブック", "反復する発見を医療、代理店、地域サービス、商取引向けに再利用します。"], ["チャネルパートナー", "コンサルタントやソフトウェア企業が適格な事業をPerkOSへ導きます。"], ["テンプレート循環", "成功した導入が非公開カタログを改善し、次の価値創出を速めます。"]] },
  moat: { ...en.moat, section: "競争優位", kicker: "蓄積する優位性", title: "防御力は", accent: "閉じたループにある。", intro: "単機能は模倣できます。PerkOSは発見、設計、実行文脈、相互運用、検証可能な運用を横断して蓄積します。", layers: [["発見データ", "企業が本当に必要とするものの構造化された証拠。"], ["ソリューション設計", "ニーズ、役割、フローを結ぶ再利用可能な非公開パターン。"], ["コンテキストプレーン", "最新のプロジェクト情報を各ランタイムへ安全に提供。"], ["ランタイムネットワーク", "モデルロックインなしで管理・外部エージェントを接続。"], ["信頼レール", "ID、認可、利用、レシート、任意の決済。"]], flywheel: "導入増加 → 設計改善 → 成果高速化 → 流通強化。", compound: "蓄積システム", layer: "レイヤー" },
  roadmap: { ...en.roadmap, section: "ロードマップ", kicker: "これから", title: "次の", accent: "12か月。", badge: "将来計画", intro: "既存製品をつなぎ、成功したソリューションを再現可能、スケーラブル、そして継続的に改善するものへ進化させます。", focuses: ["発見から導入までを閉じる", "ソリューションを再現可能に", "運用レイヤーを拡張", "ネットワークへ蓄積"], details: [["PerkOS内のネイティブGrow", "非公開設計と人のレビュー", "オンボーディングと可観測性統合"], ["業界別ソリューション", "成果測定ループ", "デザインパートナー導入手順"], ["大規模マルチテナント運用", "非公開ソリューションカタログ", "利用・請求・パートナー制御"], ["自己改善するソリューション網", "組織間エージェントサービス", "任意のM2Mコマース"]] },
  close: { ...en.close, kicker: "ビジョン", title: "すべての企業が", accent: "AIチームと運営できる未来。", copy: "PerkOSは、最初の質問から稼働チームまで、事業の意図を責任あるAIの仕事に変えるシステムを構築しています。", explore: "PerkOSを見る", partners: ["デザインパートナー", "エコシステムパートナー", "投資家"] },
};

const ko: DeckCopy = {
  ...ja,
  nav: { deck: "투자자 덱", present: "프레젠테이션", slides: "장 · 원하는 슬라이드에서 시작하세요", hint: "진지하고 간결한 투자자 대화용 · 재무 금액 없음", next: "다음 슬라이드", previous: "이전 슬라이드", exit: "프레젠테이션 종료", investorOverview: "투자자 개요" },
  hero: { eyebrow: "실제 업무를 수행하는 AI 팀", title: "비즈니스 문제에서", accent: "책임 있는 AI 팀으로.", copy: "PerkOS는 AI가 가치를 만들 지점을 찾고, 적합한 팀을 구성하며, 그 팀이 실제로 일할 운영 계층을 제공합니다." },
  problem: { ...ja.problem, section: "문제", kicker: "도입 격차", title: "AI 도입에는", accent: "번역의 격차가 있습니다.", intro: "모델은 더 강력해지고 있지만 기업은 그 역량을 일상 운영의 신뢰 가능한 업무로 바꾸는 데 여전히 어려움을 겪습니다.", items: [["올바른 문제 찾기", "AI가 중요하다는 것은 알지만 어디서 측정 가능한 가치를 만들지는 모릅니다."], ["맥락 번역하기", "범용 코파일럿은 업무 프로세스, 제약, 지식을 이해하지 못합니다."], ["답변을 실행으로", "좋은 답변 뒤에도 도구, 후속 조치, 실행의 조정은 사람에게 남습니다."], ["신뢰하고 측정하기", "책임, 승인, 증거, 성과가 없으면 AI는 실험에 머뭅니다."]], insight: "병목은 지능에 대한 접근이 아니라 지능을 운영 역량으로 바꾸는 일입니다." },
  thesis: { ...ja.thesis, section: "투자 논지", kicker: "우리의 논지", title: "모델이 곧 제품은 아닙니다.", accent: "그 주변의 운영체제가 제품입니다.", copy: "PerkOS는 비즈니스 의도와 AI 실행 사이의 컨트롤 플레인입니다. 맥락, 팀, 워크플로, 승인, 증거, 인프라를 하나로 연결합니다.", center: "운영 계층", rails: ["비즈니스 맥락", "사람 + 에이전트", "통제 + 신뢰", "성과 + 증거"] },
  loop: { ...ja.loop, section: "시스템", kicker: "PerkOS 작동 방식", title: "또 하나의 단일 도구가 아닌,", accent: "연속적인 운영 루프.", steps: [["발견", "비즈니스를 이해하고 가장 가치 높은 기회를 찾습니다."], ["설계", "증거를 비공개 구조화 블루프린트로 바꿉니다."], ["구성", "역할, 지식, 도구, 런타임을 설정합니다."], ["운영", "프로젝트, 업무, 채팅, 승인을 조율합니다."], ["개선", "성과를 다음 배포에 반영합니다."]], cycle: "다음 사이클로 연결", principles: [["비즈니스 우선", "모델이 아닌 측정 가능한 필요에서 시작합니다."], ["사람의 통제", "승인과 경계를 명확히 유지합니다."], ["런타임 중립", "PerkOS 관리형 또는 외부 AI를 사용합니다."]] },
  surfaces: { ...ja.surfaces, section: "제품 아키텍처", kicker: "제품 영역", title: "세 개의 영역.", accent: "하나의 시스템.", items: [{ label: "01 · 발견", title: "PerkOS Grow", copy: "적응형 진단이 요구를 기회 지도, 보고서, 기계가 읽는 비공개 아티팩트로 전환합니다.", foot: "공개 입력 · 사용자 보고서 · 내부 JSON" }, { label: "02 · 운영", title: "PerkOS App", copy: "조직이 팀을 시작하고, 프로젝트와 업무를 조율하며, 맥락을 유지하고 모든 참여자와 소통합니다.", foot: "프로젝트 · 업무 · 문서 · 채팅 · 승인" }, { label: "03 · 연결", title: "PerkOS Infrastructure", copy: "모델을 강제하지 않고 관리형 에이전트와 OpenClaw, Hermes, 커스텀 런타임을 연결합니다.", foot: "A2A · 모델 게이트웨이 · Knowledge · 신원 · 결제" }], summary: "각 영역은 독립적으로 가치가 있고, 함께 발견에서 운영까지의 순환을 만듭니다." },
  live: { ...ja.live, section: "실행", kicker: "구축 및 운영 중", title: "현재 이미", accent: "운영 중인 기반.", badge: "프로덕션 기반", intro: "플랫폼은 이미 발견, 운영, 런타임 연결, 맥락, 모델, 지식을 포괄합니다. 다음 단계는 이를 반복 가능한 고객 여정으로 연결하는 것입니다.", items: [["적응형 발견", "Grow 인터뷰, 이메일 인증, 다국어 보고서, 비공개 PDF와 JSON."], ["프로젝트 운영", "조직, 프로젝트, 업무, 문서, 직접·프로젝트 채팅, 팀."], ["외부 런타임", "OpenClaw와 Hermes 공식 설치·복구 및 양방향 PerkOS Chat."], ["컨텍스트 플레인", "실행 전 프로젝트, 대화, 팀, 업무, 증거의 정확한 맥락 제공."], ["모델 게이트웨이", "다중 제공자 라우팅, 계측, 동시성 제어, 자체 모델 지원."], ["Knowledge 계층", "리서치 요청, 증거, 검색, 재사용 가능한 조직 지식."]], note: "‘운영 중’은 배포된 기능과 프로덕션 승인 테스트를 뜻하며 매출이나 고객 규모를 의미하지 않습니다." },
  proof: { ...ja.proof, section: "아키텍처 검증", kicker: "PerkOS Council", title: "연출된 챗봇 데모가 아닌,", accent: "실제 이기종 AI 팀.", team: "프로젝트 팀", connected: "연결됨", roles: ["OpenClaw · 코디네이터", "OpenClaw · 외부", "OpenClaw · 외부", "Hermes · 외부", "OpenClaw · 외부", "OpenClaw · 외부"], model: "모델 선택은 런타임이 소유합니다. PerkOS는 에이전트의 모델을 강제하지 않고 업무를 조율합니다.", items: [["양방향 통신", "프로젝트 채팅에서 외부 런타임으로 전달되고 답변이 같은 대화에 돌아옵니다."], ["신뢰 가능한 맥락", "각 실행은 최신 팀, 코디네이터, 업무, 문서, 대화 범위를 받습니다."], ["설계된 격리", "테넌트, 프로젝트, 대화, 자격 증명, 런타임 경계가 사용자 혼합을 막습니다."]] },
  business: { ...ja.business, section: "비즈니스 모델", kicker: "상업 엔진", title: "문제로 진입하고,", accent: "성과로 확장합니다.", intro: "진단, 솔루션 배포, 반복 운영, 추가 워크플로 확장이라는 고객 여정 자체가 모델이 됩니다.", phases: [["진입", "진단", "유용한 진단이 신뢰를 만들고 첫 고가치 워크플로를 찾습니다."], ["출시", "배포", "솔루션, 역할, 연동, 지식, 통제를 구성합니다."], ["반복", "운영", "고객은 프로젝트, 승인, 보고, 지속적인 AI 사용으로 돌아옵니다."], ["확장", "축적", "새로운 흐름, 템플릿, 파트너, 에이전트 서비스로 넓어집니다."]], revenues: ["솔루션 설계 및 구현", "플랫폼·런타임·모델 사용", "파트너 유통 및 에이전트 서비스"] },
  gtm: { ...ja.gtm, section: "시장 진출", kicker: "집중된 유통", title: "고통이 구체적인 곳에서 시작해", accent: "반복되는 것을 확장합니다.", wedgeTitle: "진입점은 ‘모두를 위한 AI’가 아닙니다.", wedge: "명확한 책임자, 측정 가능한 마찰, 진단에서 배포까지의 경로를 가진 실제 비즈니스의 구체적 워크플로입니다.", grow: "Grow는 이 전략의 입구이자 학습 시스템입니다.", stages: [["디자인 파트너", "운영 문제가 명확하고 빈번한 기업과 긴밀히 협력합니다."], ["산업별 플레이북", "반복되는 발견을 병원, 에이전시, 로컬 서비스, 커머스에 재사용합니다."], ["채널 파트너", "컨설턴트와 소프트웨어 파트너가 적합한 기업을 PerkOS로 연결합니다."], ["템플릿 순환", "성공한 배포가 비공개 카탈로그를 개선하고 다음 가치 창출을 단축합니다."]] },
  moat: { ...ja.moat, section: "방어력", kicker: "누적되는 우위", title: "해자는", accent: "닫힌 루프입니다.", intro: "단일 기능은 복제할 수 있습니다. PerkOS는 발견, 설계, 실행 맥락, 상호운용성, 검증 가능한 운영 전반에서 우위를 축적합니다.", layers: [["발견 데이터", "기업이 실제로 필요로 하는 것에 대한 구조화된 증거."], ["솔루션 블루프린트", "요구, 역할, 워크플로를 잇는 재사용 가능한 비공개 패턴."], ["컨텍스트 플레인", "최신 프로젝트 사실을 각 런타임에 안전하게 전달."], ["런타임 네트워크", "모델 종속 없이 관리형·외부 에이전트를 연결."], ["신뢰 레일", "신원, 권한, 사용, 영수증, 선택적 결제."]], flywheel: "더 많은 배포 → 더 나은 설계 → 더 빠른 성과 → 더 강한 유통.", compound: "누적 시스템", layer: "계층" },
  roadmap: { ...ja.roadmap, section: "로드맵", kicker: "앞으로의 방향", title: "다음", accent: "12개월.", badge: "향후 계획", intro: "현재 제품을 연결하고 성공한 솔루션을 반복 가능하고 확장 가능하며 지속적으로 개선되는 시스템으로 발전시킵니다.", focuses: ["발견에서 배포까지 연결", "솔루션 반복 가능화", "운영 계층 확장", "네트워크로 축적"], details: [["PerkOS 내 네이티브 Grow", "비공개 설계와 사람 검토", "온보딩·관측성 통합"], ["산업별 솔루션 템플릿", "성과 측정 루프", "디자인 파트너 배포 절차"], ["대규모 멀티테넌트 조율", "비공개 솔루션 카탈로그", "사용·청구·파트너 통제"], ["스스로 개선되는 솔루션망", "조직 간 에이전트 서비스", "선택적 M2M 커머스"]] },
  close: { ...ja.close, kicker: "비전", title: "모든 기업이", accent: "AI 팀과 함께 운영되는 미래.", copy: "PerkOS는 첫 질문부터 운영 팀까지 비즈니스 의도를 책임 있는 AI 업무로 바꾸는 시스템을 구축합니다.", explore: "PerkOS 살펴보기", partners: ["디자인 파트너", "생태계 파트너", "투자자"] },
};

export const DECK_COPY: Record<PublicDeckLanguage, DeckCopy> = { en, es, fr, pt, ja, ko };

export function useDeckCopy() {
  const { i18n } = useTranslation();
  const candidate = (i18n.resolvedLanguage || i18n.language || "en").split("-")[0] as PublicDeckLanguage;
  const language: PublicDeckLanguage = candidate in DECK_COPY ? candidate : "en";
  return { copy: DECK_COPY[language], language };
}

