"use client";

import { useTranslation } from "react-i18next";

type PublicDeckLanguage = "en" | "es" | "fr" | "pt" | "ja" | "ko";

type Pair = [string, string];
type Triple = [string, string, string];

export type DeckCopy = {
  nav: { deck: string; present: string; slides: string; hint: string; next: string; previous: string; exit: string; investorOverview: string };
  hero: { eyebrow: string; title: string; accent: string; copy: string };
  problem: { section: string; kicker: string; title: string; accent: string; intro: string; items: Pair[]; insight: string };
  thesis: { section: string; kicker: string; title: string; accent: string; copy: string; center: string; rails: string[] };
  loop: { section: string; kicker: string; title: string; accent: string; steps: Pair[]; cycle: string; principles: Pair[] };
  surfaces: { section: string; kicker: string; title: string; accent: string; items: { label: string; title: string; copy: string; foot: string }[]; summary: string };
  live: { section: string; kicker: string; title: string; accent: string; badge: string; intro: string; items: Pair[]; note: string };
  proof: { section: string; kicker: string; title: string; accent: string; team: string; connected: string; roles: string[]; model: string; items: Pair[] };
  business: { section: string; kicker: string; title: string; accent: string; intro: string; phases: Triple[]; revenues: string[] };
  gtm: { section: string; kicker: string; title: string; accent: string; wedgeTitle: string; wedge: string; grow: string; stages: Pair[] };
  moat: { section: string; kicker: string; title: string; accent: string; intro: string; layers: Pair[]; flywheel: string; compound: string; layer: string };
  roadmap: { section: string; kicker: string; title: string; accent: string; badge: string; intro: string; focuses: string[]; details: string[][] };
  close: { kicker: string; title: string; accent: string; copy: string; explore: string; partners: string[] };
};

const en: DeckCopy = {
  nav: { deck: "Investor deck", present: "Present", slides: "slides · click any slide to present from there", hint: "Built for a concise investor conversation · no financial amounts", next: "Next slide", previous: "Previous slide", exit: "Exit presentation", investorOverview: "Investor overview" },
  hero: { eyebrow: "AI teams for real business work", title: "From business problem to", accent: "accountable AI team.", copy: "PerkOS discovers where AI can create value, assembles the right team, and provides the operating layer to put that team to work." },
  problem: { section: "The problem", kicker: "Two niches, one gap", title: "AI adoption has a", accent: "translation gap.", intro: "Take two businesses that look nothing alike. An independent medical practice, and an auto parts distributor selling to workshops. Both lose revenue in exactly the same place.", items: [["The work arrives as a message", "A patient asks for an appointment. A workshop asks whether a part fits a 2018 pickup. Neither arrives as structured data."], ["The answer needs private context", "It depends on the schedule and the insurance rules, or on the catalog, the stock, and that customer's price list."], ["One person is the bottleneck", "The front desk answers the phone while patients wait. The counter quotes one workshop while three others go unanswered."], ["Slow answers are lost revenue", "An unconfirmed appointment becomes a no-show. A quote that takes two hours becomes someone else's sale."]], insight: "Two industries with nothing in common, and the same operating shape: unstructured demand meeting private context, with one person in the middle." },
  thesis: { section: "Investment thesis", kicker: "Our thesis", title: "The model is not the product.", accent: "The operating system around it is.", copy: "PerkOS is the control plane between business intent and AI execution: context, teams, workflows, approvals, evidence, and infrastructure in one system.", center: "Operating layer", rails: ["Business context", "People + agents", "Control + trust", "Outcomes + evidence"] },
  loop: { section: "The system", kicker: "How PerkOS works", title: "One continuous operating loop,", accent: "not another point solution.", steps: [["Discover", "Understand the business and find the highest-value opportunity."], ["Design", "Turn evidence into a private, structured solution blueprint."], ["Assemble", "Configure the right roles, knowledge, tools, and runtime."], ["Operate", "Coordinate work through projects, tasks, chat, and approvals."], ["Improve", "Use artifacts and outcomes to strengthen the next deployment."]], cycle: "Feeds the next cycle", principles: [["Business-first", "Start with a measurable need, not a model."], ["Human-controlled", "Approvals and boundaries remain explicit."], ["Runtime-agnostic", "Use PerkOS-managed or external AI runtimes."]] },
  surfaces: { section: "Product architecture", kicker: "Product surfaces", title: "Three surfaces.", accent: "One system.", items: [{ label: "01 · DISCOVER", title: "PerkOS Grow", copy: "Adaptive business diagnostics turn unstructured needs into opportunity maps, reports, and a private machine-readable solution artifact.", foot: "Public intake · human-readable report · internal JSON" }, { label: "02 · OPERATE", title: "PerkOS App", copy: "Organizations launch teams, create projects, coordinate tasks, maintain project context, and communicate with every participant.", foot: "Projects · tasks · documents · chat · approvals" }, { label: "03 · CONNECT", title: "PerkOS Infrastructure", copy: "A runtime-neutral foundation connects managed agents and external OpenClaw, Hermes, or custom runtimes without owning their model choices.", foot: "A2A · model gateway · Knowledge · identity · settlement" }], summary: "Each surface is valuable alone. Together they create the discovery-to-operation flywheel." },
  live: { section: "Execution", kicker: "Built and running", title: "What is", accent: "live today.", badge: "Production foundation", intro: "The current platform already spans discovery, operations, runtime connectivity, context, models, and knowledge. The next phase connects these pieces into one repeatable customer journey.", items: [["Adaptive discovery", "Grow interviews, email verification, localized reports, private PDF and JSON artifacts."], ["Project operations", "Organizations, projects, tasks, documents, direct chat, project chat, and team rosters."], ["External runtimes", "Official install and repair flows for OpenClaw and Hermes with two-way PerkOS Chat."], ["Context plane", "Authoritative project, conversation, roster, task, and evidence context before execution."], ["Model gateway", "Multi-provider routing, metering, concurrency control, and bring-your-own-model support."], ["Knowledge layer", "Research requests, evidence metadata, retrieval, and reusable organizational knowledge."]], note: "“Live” describes deployed product capabilities and production acceptance tests. It does not imply commercial revenue or customer volume." },
  proof: { section: "Proof of architecture", kicker: "PerkOS Council", title: "A real heterogeneous team,", accent: "not a staged chatbot demo.", team: "Project team", connected: "Connected", roles: ["OpenClaw · coordinator", "OpenClaw · external", "OpenClaw · external", "Hermes · external", "OpenClaw · external", "OpenClaw · external"], model: "Runtime-owned model routing. PerkOS coordinates work without forcing the agent's model.", items: [["Two-way communication", "Messages travel from Project Chat to each external runtime and replies return visibly to the same conversation."], ["Authoritative context", "Every run receives the current project roster, coordinator, tasks, documents, and conversation scope."], ["Isolation by design", "Tenant, project, conversation, credential, and runtime boundaries prevent context from bleeding between users."]] },
  business: { section: "Business model", kicker: "Commercial engine", title: "Land with a problem.", accent: "Expand with results.", intro: "Both niches buy the same way: a small operator with a visible, expensive bottleneck, an owner who decides in a single conversation, and a workflow that either pays back in weeks or does not.", phases: [["ENTRY", "Diagnose", "One workflow, measured. Appointments confirmed per week, or quotes answered per day."], ["LAUNCH", "Deploy", "The practice or the counter goes live on its own schedule, catalog, price lists, and approval rules."], ["RECURRING", "Operate", "The team returns every day to the same inbox, board, and approvals. Usage grows with the business."], ["EXPANSION", "Compound", "Recalls and billing follow appointments. Backorders and receivables follow quoting."]], revenues: ["Setup and workflow configuration", "Monthly operation per practice or counter", "Channel partners and vertical software"] },
  gtm: { section: "Go to market", kicker: "Two beachheads", title: "Start where the pain is specific.", accent: "Scale what repeats.", wedgeTitle: "Our wedge is two niches, not a list of industries.", wedge: "Independent medical practices, and auto parts distributors selling B2B to workshops. Both are small, both are decided by the owner, and both run on inbound requests that a person has to translate by hand.", grow: "Grow is the front door: a diagnostic that qualifies the business and produces the deployment brief.", stages: [["Independent medical practices", "One to five doctors, where the front desk sits between the patient and the schedule, and a no-show costs a full slot."], ["Auto parts distributors", "Counters selling to workshops, where the first quote wins the order and the catalog lives in someone's head."], ["Channel partners", "The people already inside these businesses: practice management software, parts catalog providers, accountants, and local consultants."], ["Template flywheel", "Every deployment sharpens the playbook for the next one, so the tenth costs a fraction of the first."]] },
  moat: { section: "Defensibility", kicker: "The compounding advantage", title: "The moat is the", accent: "closed loop.", intro: "Point tools can copy a feature. PerkOS compounds across discovery, solution design, execution context, runtime interoperability, and verifiable operations.", layers: [["Discovery data", "Structured evidence about what businesses actually need."], ["Solution blueprints", "Reusable private patterns that map needs to roles and workflows."], ["Context plane", "Current project truth delivered safely to every participating runtime."], ["Runtime network", "Managed and external agents connected without model lock-in."], ["Trust rails", "Identity, authorization, usage, receipts, and optional settlement."]], flywheel: "More deployments → better blueprints → faster outcomes → stronger distribution.", compound: "Compounding system", layer: "LAYER" },
  roadmap: { section: "Roadmap", kicker: "Where we are going", title: "The next", accent: "twelve months.", badge: "Forward plan", intro: "The roadmap moves from connecting today's products to making successful solutions repeatable, scalable, and increasingly self-improving.", focuses: ["Close the discovery-to-deployment loop", "Make solutions repeatable", "Scale the operating layer", "Compound into a network"], details: [["Native Grow workflow inside PerkOS", "Private blueprint and reviewer path", "Unified onboarding and observability"], ["Vertical solution templates", "Outcome measurement loop", "Design-partner deployment playbook"], ["Multi-tenant orchestration at scale", "Private solution catalog", "Usage, billing, and partner controls"], ["Self-improving solution network", "Cross-organization agent services", "Optional machine-to-machine commerce"]] },
  close: { kicker: "The vision", title: "Every business should be able to operate with an", accent: "AI team.", copy: "PerkOS is building the system that turns business intent into accountable AI work — from the first question to the operating team.", explore: "Explore PerkOS", partners: ["Design partners", "Ecosystem partners", "Investors"] },
};

const es: DeckCopy = {
  nav: { deck: "Deck para inversionistas", present: "Presentar", slides: "láminas · haz clic en una para presentar desde allí", hint: "Diseñado para una conversación seria y concisa · sin montos financieros", next: "Siguiente lámina", previous: "Lámina anterior", exit: "Salir de la presentación", investorOverview: "Presentación para inversionistas" },
  hero: { eyebrow: "Equipos de IA para trabajo real", title: "De un problema de negocio a un", accent: "equipo de IA responsable.", copy: "PerkOS descubre dónde la IA puede crear valor, arma el equipo correcto y aporta la capa operativa para ponerlo a trabajar." },
  problem: { section: "El problema", kicker: "Dos nichos, una misma brecha", title: "La adopción de IA tiene una", accent: "brecha de traducción.", intro: "Tomemos dos negocios que no se parecen en nada. Un consultorio médico independiente y un almacén de repuestos que vende a talleres. Los dos pierden ingresos exactamente en el mismo punto.", items: [["El trabajo llega como mensaje", "Un paciente pide turno. Un taller pregunta si una pieza entra en una camioneta 2018. Ninguno llega como dato estructurado."], ["Responder exige contexto propio", "Depende de la agenda y las reglas de la obra social, o del catálogo, el stock y la lista de precios de ese cliente."], ["Una sola persona es el cuello de botella", "La recepción atiende el teléfono mientras hay pacientes esperando. El mostrador cotiza a un taller mientras otros tres quedan sin respuesta."], ["Responder tarde es perder la venta", "Un turno sin confirmar termina en ausencia. Una cotización que tarda dos horas termina siendo la venta de otro."]], insight: "Dos rubros sin nada en común y la misma forma operativa: demanda desordenada contra contexto propio, con una persona en el medio." },
  thesis: { section: "Tesis de inversión", kicker: "Nuestra tesis", title: "El modelo no es el producto.", accent: "El sistema operativo a su alrededor sí.", copy: "PerkOS es el plano de control entre la intención del negocio y la ejecución de IA: contexto, equipos, flujos, aprobaciones, evidencia e infraestructura en un solo sistema.", center: "Capa operativa", rails: ["Contexto del negocio", "Personas + agentes", "Control + confianza", "Resultados + evidencia"] },
  loop: { section: "El sistema", kicker: "Cómo funciona PerkOS", title: "Un ciclo operativo continuo,", accent: "no otra solución aislada.", steps: [["Descubrir", "Entender el negocio y encontrar la oportunidad de mayor valor."], ["Diseñar", "Convertir la evidencia en un blueprint privado y estructurado."], ["Armar", "Configurar roles, conocimiento, herramientas y runtime."], ["Operar", "Coordinar proyectos, tareas, chat y aprobaciones."], ["Mejorar", "Usar artefactos y resultados para fortalecer el siguiente despliegue."]], cycle: "Alimenta el siguiente ciclo", principles: [["Primero el negocio", "Partir de una necesidad medible, no de un modelo."], ["Control humano", "Aprobaciones y límites siempre explícitos."], ["Independiente del runtime", "Usar IA administrada por PerkOS o runtimes externos."]] },
  surfaces: { section: "Arquitectura de producto", kicker: "Superficies del producto", title: "Tres superficies.", accent: "Un solo sistema.", items: [{ label: "01 · DESCUBRIR", title: "PerkOS Grow", copy: "Diagnósticos adaptativos convierten necesidades dispersas en mapas de oportunidades, reportes y un artefacto privado legible por máquinas.", foot: "Captura pública · reporte humano · JSON interno" }, { label: "02 · OPERAR", title: "PerkOS App", copy: "Las organizaciones lanzan equipos, crean proyectos, coordinan tareas, conservan contexto y se comunican con cada participante.", foot: "Proyectos · tareas · documentos · chat · aprobaciones" }, { label: "03 · CONECTAR", title: "Infraestructura PerkOS", copy: "Una base neutral conecta agentes administrados y runtimes externos OpenClaw, Hermes o custom sin imponerles un modelo.", foot: "A2A · gateway de modelos · Knowledge · identidad · liquidación" }], summary: "Cada superficie tiene valor por sí sola. Juntas crean el ciclo de descubrimiento a operación." },
  live: { section: "Ejecución", kicker: "Construido y operando", title: "Lo que está", accent: "activo hoy.", badge: "Base en producción", intro: "La plataforma ya cubre descubrimiento, operaciones, conectividad de runtimes, contexto, modelos y conocimiento. La siguiente fase los une en un recorrido repetible para el cliente.", items: [["Descubrimiento adaptativo", "Entrevistas Grow, verificación de email, reportes localizados y artefactos privados PDF y JSON."], ["Operación de proyectos", "Organizaciones, proyectos, tareas, documentos, chat directo, chat de proyecto y equipos."], ["Runtimes externos", "Flujos oficiales de instalación y reparación para OpenClaw y Hermes con chat bidireccional."], ["Plano de contexto", "Contexto autoritativo de proyecto, conversación, equipo, tareas y evidencia antes de ejecutar."], ["Gateway de modelos", "Routing multiproveedor, medición, control de concurrencia y modelos propios."], ["Capa de conocimiento", "Solicitudes de research, evidencia, recuperación y conocimiento organizacional reutilizable."]], note: "“Activo” describe capacidades desplegadas y pruebas de aceptación en producción. No implica ingresos ni volumen de clientes." },
  proof: { section: "Prueba de arquitectura", kicker: "PerkOS Council", title: "Un equipo heterogéneo real,", accent: "no una demo preparada.", team: "Equipo del proyecto", connected: "Conectado", roles: ["OpenClaw · coordinador", "OpenClaw · externo", "OpenClaw · externo", "Hermes · externo", "OpenClaw · externo", "OpenClaw · externo"], model: "El runtime controla su modelo. PerkOS coordina el trabajo sin imponer el modelo del agente.", items: [["Comunicación bidireccional", "Los mensajes viajan del Chat del proyecto al runtime externo y las respuestas vuelven a la misma conversación."], ["Contexto autoritativo", "Cada ejecución recibe equipo, coordinador, tareas, documentos y alcance de conversación vigentes."], ["Aislamiento por diseño", "Los límites de tenant, proyecto, conversación, credencial y runtime evitan mezclar usuarios."]] },
  business: { section: "Modelo de negocio", kicker: "Motor comercial", title: "Entrar con un problema.", accent: "Crecer con resultados.", intro: "Los dos nichos compran igual: un negocio chico con un cuello de botella visible y caro, un dueño que decide en una sola conversación y un flujo que se paga en semanas o no se paga.", phases: [["ENTRADA", "Diagnosticar", "Un solo flujo, medido. Turnos confirmados por semana, o cotizaciones respondidas por día."], ["LANZAMIENTO", "Desplegar", "El consultorio o el mostrador arranca con su propia agenda, catálogo, listas de precios y reglas de aprobación."], ["RECURRENCIA", "Operar", "El equipo vuelve todos los días a la misma bandeja, al mismo tablero y a las mismas aprobaciones. El uso crece con el negocio."], ["EXPANSIÓN", "Multiplicar", "Después de los turnos vienen los controles y la facturación. Después de cotizar vienen los pedidos y la cuenta corriente."]], revenues: ["Implementación y configuración del flujo", "Operación mensual por consultorio o sucursal", "Socios de canal y software vertical"] },
  gtm: { section: "Salida al mercado", kicker: "Dos cabezas de playa", title: "Empezar donde el dolor es específico.", accent: "Escalar lo que se repite.", wedgeTitle: "Nuestra entrada son dos nichos, no una lista de rubros.", wedge: "Consultorios médicos independientes y almacenes de repuestos que venden B2B a talleres. Los dos son chicos, los dos deciden por dueño y los dos viven de pedidos que entran sueltos y alguien tiene que traducir a mano.", grow: "Grow es la puerta de entrada: un diagnóstico que califica al negocio y deja armado el brief de despliegue.", stages: [["Consultorios médicos independientes", "De uno a cinco profesionales, donde la recepción está entre el paciente y la agenda, y una ausencia cuesta un turno entero."], ["Almacenes de repuestos", "Mostradores que venden a talleres, donde cotizar primero gana el pedido y el catálogo vive en la cabeza de alguien."], ["Socios de canal", "Los que ya están adentro de estos negocios: software de gestión, proveedores de catálogo, contadores y consultores locales."], ["Ciclo de plantillas", "Cada despliegue afila el playbook del siguiente, y el décimo cuesta una fracción del primero."]] },
  moat: { section: "Defensibilidad", kicker: "La ventaja acumulativa", title: "El moat es el", accent: "ciclo cerrado.", intro: "Una herramienta puntual puede copiar una función. PerkOS acumula ventaja en descubrimiento, diseño, contexto de ejecución, interoperabilidad y operación verificable.", layers: [["Datos de descubrimiento", "Evidencia estructurada de lo que los negocios realmente necesitan."], ["Blueprints de solución", "Patrones privados reutilizables que conectan necesidades, roles y flujos."], ["Plano de contexto", "La verdad vigente del proyecto llega de forma segura a cada runtime."], ["Red de runtimes", "Agentes administrados y externos sin dependencia de un modelo."], ["Rieles de confianza", "Identidad, autorización, uso, recibos y liquidación opcional."]], flywheel: "Más despliegues → mejores blueprints → resultados más rápidos → mayor distribución.", compound: "Sistema acumulativo", layer: "CAPA" },
  roadmap: { section: "Roadmap", kicker: "Hacia dónde vamos", title: "Los próximos", accent: "doce meses.", badge: "Plan de avance", intro: "El roadmap conecta los productos actuales y convierte soluciones exitosas en capacidades repetibles, escalables y cada vez más autónomas.", focuses: ["Cerrar el ciclo de descubrimiento a despliegue", "Volver repetibles las soluciones", "Escalar la capa operativa", "Convertirse en una red"], details: [["Grow nativo dentro de PerkOS", "Blueprint privado y revisión humana", "Onboarding y observabilidad unificados"], ["Plantillas verticales de solución", "Ciclo de medición de resultados", "Playbook para socios de diseño"], ["Orquestación multi-tenant a escala", "Catálogo privado de soluciones", "Uso, facturación y controles de socios"], ["Red de soluciones que aprende", "Servicios entre organizaciones", "Comercio opcional máquina a máquina"]] },
  close: { kicker: "La visión", title: "Toda empresa debería poder operar con un", accent: "equipo de IA.", copy: "PerkOS construye el sistema que convierte intención de negocio en trabajo de IA responsable: desde la primera pregunta hasta el equipo operativo.", explore: "Conocer PerkOS", partners: ["Socios de diseño", "Socios de ecosistema", "Inversionistas"] },
};

const fr: DeckCopy = {
  ...en,
  nav: { deck: "Deck investisseurs", present: "Présenter", slides: "diapositives · cliquez pour démarrer à cet endroit", hint: "Conçu pour un échange investisseur concis · sans montants financiers", next: "Diapositive suivante", previous: "Diapositive précédente", exit: "Quitter la présentation", investorOverview: "Présentation investisseurs" },
  hero: { eyebrow: "Des équipes IA pour le travail réel", title: "Du problème métier à une", accent: "équipe IA responsable.", copy: "PerkOS identifie où l’IA crée de la valeur, assemble la bonne équipe et fournit la couche opérationnelle qui la met au travail." },
  problem: { ...en.problem, section: "Le problème", kicker: "Deux niches, un même fossé", title: "L’adoption de l’IA souffre d’un", accent: "fossé de traduction.", intro: "Prenons deux entreprises qui n’ont rien en commun. Un cabinet médical indépendant et un distributeur de pièces détachées qui vend aux garages. Les deux perdent du chiffre exactement au même endroit.", items: [["Le travail arrive en message", "Un patient demande un rendez-vous. Un garage demande si une pièce va sur un pick-up de 2018. Aucun n’arrive en donnée structurée."], ["Répondre exige un contexte propre", "Cela dépend de l’agenda et des règles de la mutuelle, ou du catalogue, du stock et du tarif de ce client."], ["Une seule personne fait goulot", "L’accueil répond au téléphone pendant que les patients attendent. Le comptoir chiffre un garage pendant que trois autres restent sans réponse."], ["Répondre tard, c’est perdre la vente", "Un rendez-vous non confirmé devient une absence. Un devis qui prend deux heures devient la vente d’un autre."]], insight: "Deux secteurs sans rien en commun et la même forme opérationnelle : une demande désordonnée face à un contexte propre, avec une personne au milieu." },
  thesis: { ...en.thesis, section: "Thèse d’investissement", kicker: "Notre thèse", title: "Le modèle n’est pas le produit.", accent: "Le système d’exploitation autour de lui l’est.", copy: "PerkOS est le plan de contrôle entre l’intention métier et l’exécution IA : contexte, équipes, workflows, validations, preuves et infrastructure réunis.", center: "Couche opérationnelle", rails: ["Contexte métier", "Humains + agents", "Contrôle + confiance", "Résultats + preuves"] },
  loop: { ...en.loop, section: "Le système", kicker: "Comment fonctionne PerkOS", title: "Une boucle opérationnelle continue,", accent: "pas un outil isolé.", steps: [["Découvrir", "Comprendre l’entreprise et repérer l’opportunité prioritaire."], ["Concevoir", "Transformer les preuves en blueprint privé et structuré."], ["Assembler", "Configurer les rôles, connaissances, outils et runtime."], ["Opérer", "Coordonner projets, tâches, chat et validations."], ["Améliorer", "Utiliser les résultats pour renforcer le prochain déploiement."]], cycle: "Alimente le cycle suivant", principles: [["Métier d’abord", "Partir d’un besoin mesurable, pas d’un modèle."], ["Contrôle humain", "Validations et limites restent explicites."], ["Agnostique au runtime", "Utiliser l’IA PerkOS ou des runtimes externes."]] },
  surfaces: { ...en.surfaces, section: "Architecture produit", kicker: "Surfaces produit", title: "Trois surfaces.", accent: "Un seul système.", items: [{ label: "01 · DÉCOUVRIR", title: "PerkOS Grow", copy: "Des diagnostics adaptatifs transforment les besoins en cartes d’opportunités, rapports et artefact privé lisible par machine.", foot: "Collecte publique · rapport humain · JSON interne" }, { label: "02 · OPÉRER", title: "PerkOS App", copy: "Les organisations lancent des équipes, créent des projets, coordonnent les tâches, gardent le contexte et communiquent.", foot: "Projets · tâches · documents · chat · validations" }, { label: "03 · CONNECTER", title: "Infrastructure PerkOS", copy: "Une base neutre connecte agents gérés et runtimes OpenClaw, Hermes ou custom sans imposer leur modèle.", foot: "A2A · passerelle modèles · Knowledge · identité · règlement" }], summary: "Chaque surface vaut seule. Ensemble, elles créent la boucle découverte-opération." },
  live: { ...en.live, section: "Exécution", kicker: "Construit et opérationnel", title: "Ce qui est", accent: "déjà en production.", badge: "Socle en production", intro: "La plateforme couvre déjà découverte, opérations, runtimes, contexte, modèles et connaissances. La phase suivante les relie en un parcours client reproductible.", items: [["Découverte adaptative", "Entretiens Grow, vérification email, rapports localisés, PDF et JSON privés."], ["Opérations de projet", "Organisations, projets, tâches, documents, chats directs et projet, équipes."], ["Runtimes externes", "Installation et réparation officielles pour OpenClaw et Hermes avec chat bidirectionnel."], ["Plan de contexte", "Contexte fiable du projet, de la conversation, de l’équipe, des tâches et des preuves."], ["Passerelle de modèles", "Routage multi-fournisseurs, mesure, concurrence et modèles apportés par le client."], ["Couche Knowledge", "Demandes de recherche, preuves, recherche et connaissances réutilisables."]], note: "« En production » décrit des capacités déployées et testées. Cela ne suppose ni revenus ni volume client." },
  proof: { ...en.proof, section: "Preuve d’architecture", kicker: "PerkOS Council", title: "Une équipe hétérogène réelle,", accent: "pas une démo scénarisée.", team: "Équipe projet", connected: "Connecté", roles: ["OpenClaw · coordinateur", "OpenClaw · externe", "OpenClaw · externe", "Hermes · externe", "OpenClaw · externe", "OpenClaw · externe"], model: "Le runtime choisit son modèle. PerkOS coordonne sans imposer le modèle de l’agent.", items: [["Communication bidirectionnelle", "Les messages partent du chat projet vers le runtime externe et reviennent dans la même conversation."], ["Contexte de référence", "Chaque exécution reçoit l’équipe, le coordinateur, les tâches, documents et la portée à jour."], ["Isolation par conception", "Les limites tenant, projet, conversation, identifiant et runtime empêchent tout mélange."]] },
  business: { ...en.business, section: "Modèle économique", kicker: "Moteur commercial", title: "Entrer par un problème.", accent: "Grandir par les résultats.", intro: "Les deux niches achètent de la même façon : une petite structure avec un goulot visible et coûteux, un dirigeant qui décide en une conversation, et un workflow qui se rentabilise en quelques semaines ou pas du tout.", phases: [["ENTRÉE", "Diagnostiquer", "Un seul workflow, mesuré. Rendez-vous confirmés par semaine, ou devis traités par jour."], ["LANCEMENT", "Déployer", "Le cabinet ou le comptoir démarre sur son propre agenda, catalogue, tarifs et règles de validation."], ["RÉCURRENCE", "Opérer", "L’équipe revient chaque jour à la même boîte, au même tableau et aux mêmes validations. L’usage suit l’activité."], ["EXPANSION", "Composer", "Après les rendez-vous viennent les rappels et la facturation. Après les devis viennent les commandes et les comptes clients."]], revenues: ["Mise en place et configuration du workflow", "Opération mensuelle par cabinet ou comptoir", "Partenaires de distribution et logiciels métier"] },
  gtm: { ...en.gtm, section: "Mise sur le marché", kicker: "Deux têtes de pont", title: "Commencer là où la douleur est précise.", accent: "Industrialiser ce qui se répète.", wedgeTitle: "Notre point d’entrée, ce sont deux niches, pas une liste de secteurs.", wedge: "Cabinets médicaux indépendants et distributeurs de pièces détachées vendant en B2B aux garages. Petites structures, décision du dirigeant, et une activité qui vit de demandes entrantes qu’une personne doit traduire à la main.", grow: "Grow est la porte d’entrée : un diagnostic qui qualifie l’entreprise et produit le brief de déploiement.", stages: [["Cabinets médicaux indépendants", "Un à cinq praticiens, où l’accueil se tient entre le patient et l’agenda, et où une absence coûte un créneau entier."], ["Distributeurs de pièces détachées", "Des comptoirs qui vendent aux garages, où le premier devis emporte la commande et où le catalogue tient dans une tête."], ["Partenaires de distribution", "Ceux qui sont déjà dans ces entreprises : logiciels de gestion, fournisseurs de catalogues, comptables et consultants locaux."], ["Boucle de templates", "Chaque déploiement affûte le playbook du suivant, et le dixième coûte une fraction du premier."]] },
  moat: { ...en.moat, section: "Défensibilité", kicker: "L’avantage cumulatif", title: "Le moat est la", accent: "boucle fermée.", intro: "Un outil ponctuel peut copier une fonction. PerkOS cumule découverte, conception, contexte, interopérabilité et opérations vérifiables.", layers: [["Données de découverte", "Preuves structurées de ce dont les entreprises ont vraiment besoin."], ["Blueprints de solution", "Modèles privés réutilisables reliant besoins, rôles et workflows."], ["Plan de contexte", "La vérité actuelle du projet est transmise à chaque runtime."], ["Réseau de runtimes", "Agents gérés et externes sans verrouillage de modèle."], ["Rails de confiance", "Identité, autorisation, usage, reçus et règlement optionnel."]], flywheel: "Plus de déploiements → meilleurs blueprints → résultats plus rapides → meilleure distribution.", compound: "Système cumulatif", layer: "COUCHE" },
  roadmap: { ...en.roadmap, section: "Feuille de route", kicker: "Notre trajectoire", title: "Les douze", accent: "prochains mois.", badge: "Plan prospectif", intro: "La feuille de route relie les produits actuels et rend les solutions réussies reproductibles, évolutives et de plus en plus autonomes.", focuses: ["Boucler découverte et déploiement", "Rendre les solutions reproductibles", "Faire évoluer la couche opérationnelle", "Composer un réseau"], details: [["Grow natif dans PerkOS", "Blueprint privé et revue humaine", "Onboarding et observabilité unifiés"], ["Templates de solutions verticales", "Boucle de mesure des résultats", "Playbook partenaires de conception"], ["Orchestration multi-tenant à l’échelle", "Catalogue privé de solutions", "Usage, facturation et contrôle partenaires"], ["Réseau de solutions apprenant", "Services inter-organisations", "Commerce machine-à-machine optionnel"]] },
  close: { ...en.close, kicker: "La vision", title: "Chaque entreprise devrait pouvoir opérer avec une", accent: "équipe IA.", copy: "PerkOS construit le système qui transforme l’intention métier en travail IA responsable, de la première question à l’équipe opérationnelle.", explore: "Découvrir PerkOS", partners: ["Partenaires de conception", "Partenaires écosystème", "Investisseurs"] },
};

const pt: DeckCopy = {
  ...es,
  nav: { deck: "Deck para investidores", present: "Apresentar", slides: "slides · clique para apresentar a partir dali", hint: "Criado para uma conversa séria e concisa · sem valores financeiros", next: "Próximo slide", previous: "Slide anterior", exit: "Sair da apresentação", investorOverview: "Apresentação para investidores" },
  hero: { eyebrow: "Equipes de IA para trabalho real", title: "Do problema de negócio a uma", accent: "equipe de IA responsável.", copy: "A PerkOS descobre onde a IA pode gerar valor, monta a equipe certa e oferece a camada operacional para colocá-la para trabalhar." },
  problem: { ...es.problem, section: "O problema", kicker: "Dois nichos, a mesma lacuna", title: "A adoção de IA tem uma", accent: "lacuna de tradução.", intro: "Pegue dois negócios que não se parecem em nada. Um consultório médico independente e uma loja de autopeças que vende para oficinas. Os dois perdem receita exatamente no mesmo ponto.", items: [["O trabalho chega como mensagem", "Um paciente pede consulta. Uma oficina pergunta se a peça serve numa picape 2018. Nenhum chega como dado estruturado."], ["Responder exige contexto próprio", "Depende da agenda e das regras do convênio, ou do catálogo, do estoque e da tabela de preços daquele cliente."], ["Uma pessoa é o gargalo", "A recepção atende o telefone com pacientes esperando. O balcão cota para uma oficina enquanto outras três ficam sem resposta."], ["Responder tarde é perder a venda", "Uma consulta não confirmada vira falta. Um orçamento que leva duas horas vira a venda de outro."]], insight: "Dois setores sem nada em comum e a mesma forma operacional: demanda desorganizada contra contexto próprio, com uma pessoa no meio." },
  thesis: { ...es.thesis, section: "Tese de investimento", kicker: "Nossa tese", title: "O modelo não é o produto.", accent: "O sistema operacional ao redor dele é.", copy: "A PerkOS é o plano de controle entre a intenção do negócio e a execução de IA: contexto, equipes, fluxos, aprovações, evidências e infraestrutura.", center: "Camada operacional", rails: ["Contexto do negócio", "Pessoas + agentes", "Controle + confiança", "Resultados + evidências"] },
  loop: { ...es.loop, section: "O sistema", kicker: "Como a PerkOS funciona", title: "Um ciclo operacional contínuo,", accent: "não outra solução isolada.", steps: [["Descobrir", "Entender o negócio e encontrar a oportunidade de maior valor."], ["Projetar", "Transformar evidências em um blueprint privado e estruturado."], ["Montar", "Configurar funções, conhecimento, ferramentas e runtime."], ["Operar", "Coordenar projetos, tarefas, chat e aprovações."], ["Melhorar", "Usar resultados para fortalecer a próxima implantação."]], cycle: "Alimenta o próximo ciclo", principles: [["Negócio primeiro", "Começar com uma necessidade mensurável, não um modelo."], ["Controle humano", "Aprovações e limites permanecem explícitos."], ["Agnóstico ao runtime", "Usar IA PerkOS ou runtimes externos."]] },
  surfaces: { ...es.surfaces, section: "Arquitetura do produto", kicker: "Superfícies do produto", title: "Três superfícies.", accent: "Um só sistema.", items: [{ label: "01 · DESCOBRIR", title: "PerkOS Grow", copy: "Diagnósticos adaptativos transformam necessidades em mapas de oportunidades, relatórios e um artefato privado legível por máquina.", foot: "Entrada pública · relatório humano · JSON interno" }, { label: "02 · OPERAR", title: "PerkOS App", copy: "Organizações lançam equipes, criam projetos, coordenam tarefas, mantêm contexto e conversam com cada participante.", foot: "Projetos · tarefas · documentos · chat · aprovações" }, { label: "03 · CONECTAR", title: "Infraestrutura PerkOS", copy: "Uma base neutra conecta agentes gerenciados e runtimes OpenClaw, Hermes ou custom sem impor um modelo.", foot: "A2A · gateway de modelos · Knowledge · identidade · liquidação" }], summary: "Cada superfície tem valor sozinha. Juntas, criam o ciclo da descoberta à operação." },
  live: { ...es.live, section: "Execução", kicker: "Construído e operando", title: "O que está", accent: "ativo hoje.", badge: "Base em produção", intro: "A plataforma já cobre descoberta, operações, runtimes, contexto, modelos e conhecimento. A próxima fase une tudo em uma jornada repetível.", items: [["Descoberta adaptativa", "Entrevistas Grow, verificação de email, relatórios localizados, PDF e JSON privados."], ["Operações de projeto", "Organizações, projetos, tarefas, documentos, chats e equipes."], ["Runtimes externos", "Instalação e reparo oficiais para OpenClaw e Hermes com chat bidirecional."], ["Plano de contexto", "Contexto confiável de projeto, conversa, equipe, tarefas e evidências."], ["Gateway de modelos", "Roteamento multi-provedor, medição, concorrência e modelos próprios."], ["Camada de conhecimento", "Pesquisa, evidências, recuperação e conhecimento reutilizável."]], note: "“Ativo” descreve capacidades implantadas e testadas em produção. Não implica receita ou volume de clientes." },
  proof: { ...es.proof, section: "Prova de arquitetura", kicker: "PerkOS Council", title: "Uma equipe heterogênea real,", accent: "não uma demo ensaiada.", team: "Equipe do projeto", connected: "Conectado", roles: ["OpenClaw · coordenador", "OpenClaw · externo", "OpenClaw · externo", "Hermes · externo", "OpenClaw · externo", "OpenClaw · externo"], model: "O runtime controla o modelo. A PerkOS coordena sem impor o modelo do agente.", items: [["Comunicação bidirecional", "Mensagens vão do chat do projeto ao runtime externo e retornam à mesma conversa."], ["Contexto de referência", "Cada execução recebe equipe, coordenador, tarefas, documentos e escopo atuais."], ["Isolamento por design", "Limites de tenant, projeto, conversa, credencial e runtime evitam mistura entre usuários."]] },
  business: { ...es.business, section: "Modelo de negócio", kicker: "Motor comercial", title: "Entrar com um problema.", accent: "Expandir com resultados.", intro: "Os dois nichos compram do mesmo jeito: um negócio pequeno com gargalo visível e caro, um dono que decide numa conversa e um fluxo que se paga em semanas ou não se paga.", phases: [["ENTRADA", "Diagnosticar", "Um único fluxo, medido. Consultas confirmadas por semana, ou orçamentos respondidos por dia."], ["LANÇAMENTO", "Implantar", "O consultório ou o balcão entra no ar com a própria agenda, catálogo, tabelas e regras de aprovação."], ["RECORRÊNCIA", "Operar", "A equipe volta todo dia à mesma caixa, ao mesmo quadro e às mesmas aprovações. O uso cresce com o negócio."], ["EXPANSÃO", "Compor", "Depois das consultas vêm os retornos e o faturamento. Depois dos orçamentos vêm os pedidos e o contas a receber."]], revenues: ["Implantação e configuração do fluxo", "Operação mensal por consultório ou filial", "Parceiros de canal e software vertical"] },
  gtm: { ...es.gtm, section: "Estratégia de mercado", kicker: "Duas cabeças de ponte", title: "Começar onde a dor é específica.", accent: "Escalar o que se repete.", wedgeTitle: "Nossa entrada são dois nichos, não uma lista de setores.", wedge: "Consultórios médicos independentes e lojas de autopeças que vendem B2B para oficinas. Os dois são pequenos, os dois decidem pelo dono e os dois vivem de pedidos soltos que alguém precisa traduzir na mão.", grow: "Grow é a porta de entrada: um diagnóstico que qualifica o negócio e entrega o brief de implantação.", stages: [["Consultórios médicos independentes", "De um a cinco profissionais, onde a recepção fica entre o paciente e a agenda, e uma falta custa um horário inteiro."], ["Lojas de autopeças", "Balcões que vendem para oficinas, onde quem orça primeiro leva o pedido e o catálogo mora na cabeça de alguém."], ["Parceiros de canal", "Quem já está dentro desses negócios: software de gestão, fornecedores de catálogo, contadores e consultores locais."], ["Ciclo de templates", "Cada implantação afia o playbook da seguinte, e a décima custa uma fração da primeira."]] },
  moat: { ...es.moat, section: "Defensibilidade", kicker: "A vantagem cumulativa", title: "O moat é o", accent: "ciclo fechado.", intro: "Uma ferramenta pontual pode copiar uma função. A PerkOS acumula descoberta, design, contexto, interoperabilidade e operações verificáveis.", layers: [["Dados de descoberta", "Evidência estruturada do que os negócios realmente precisam."], ["Blueprints de solução", "Padrões privados reutilizáveis que ligam necessidades, funções e fluxos."], ["Plano de contexto", "A verdade atual do projeto chega com segurança a cada runtime."], ["Rede de runtimes", "Agentes gerenciados e externos sem dependência de modelo."], ["Trilhos de confiança", "Identidade, autorização, uso, recibos e liquidação opcional."]], flywheel: "Mais implantações → melhores blueprints → resultados mais rápidos → maior distribuição.", compound: "Sistema cumulativo", layer: "CAMADA" },
  roadmap: { ...es.roadmap, section: "Roadmap", kicker: "Para onde vamos", title: "Os próximos", accent: "doze meses.", badge: "Plano futuro", intro: "O roadmap conecta os produtos atuais e torna soluções bem-sucedidas repetíveis, escaláveis e cada vez mais autônomas.", focuses: ["Fechar o ciclo da descoberta à implantação", "Tornar soluções repetíveis", "Escalar a camada operacional", "Compor uma rede"], details: [["Grow nativo dentro da PerkOS", "Blueprint privado e revisão humana", "Onboarding e observabilidade unificados"], ["Templates verticais de solução", "Ciclo de medição de resultados", "Playbook de parceiros de design"], ["Orquestração multi-tenant em escala", "Catálogo privado de soluções", "Uso, faturamento e controles de parceiros"], ["Rede de soluções que aprende", "Serviços entre organizações", "Comércio máquina a máquina opcional"]] },
  close: { ...es.close, kicker: "A visão", title: "Toda empresa deveria poder operar com uma", accent: "equipe de IA.", copy: "A PerkOS constrói o sistema que transforma intenção de negócio em trabalho de IA responsável, da primeira pergunta à equipe operacional.", explore: "Conhecer a PerkOS", partners: ["Parceiros de design", "Parceiros de ecossistema", "Investidores"] },
};

const ja: DeckCopy = {
  ...en,
  nav: { deck: "投資家向け資料", present: "プレゼン表示", slides: "枚 · 任意のスライドから開始できます", hint: "投資家との簡潔な対話向け · 金額情報なし", next: "次のスライド", previous: "前のスライド", exit: "プレゼンを終了", investorOverview: "投資家向け概要" },
  hero: { eyebrow: "実務を担うAIチーム", title: "事業課題から", accent: "責任あるAIチームへ。", copy: "PerkOSはAIが価値を生む領域を発見し、最適なチームを編成し、実際に働かせる運用基盤を提供します。" },
  problem: { ...en.problem, section: "課題", kicker: "二つのニッチ、同じギャップ", title: "AI導入には", accent: "翻訳のギャップがあります。", intro: "まったく似ていない二つの事業を考えます。独立系の診療所と、整備工場に卸す自動車部品店です。両者は同じ一点で売上を失っています。", items: [["仕事はメッセージで届く", "患者は予約を求め、整備工場は部品が2018年式に合うかを尋ねます。どちらも構造化データでは届きません。"], ["回答には自社の文脈が要る", "診療枠と保険の規則、あるいはカタログ、在庫、その顧客の価格表に依存します。"], ["一人がボトルネックになる", "受付は患者を待たせながら電話に出ます。カウンターが一社に見積もる間に、三社が返答を待ちます。"], ["返答の遅れは失注になる", "未確認の予約は無断キャンセルになり、二時間かかる見積もりは他社の売上になります。"]], insight: "まったく異なる二つの業種に、同じ運用の形があります。整理されていない依頼と自社固有の文脈、その間に立つ一人です。" },
  thesis: { ...en.thesis, section: "投資テーマ", kicker: "私たちの仮説", title: "モデルそのものは製品ではない。", accent: "周囲のOSこそが製品です。", copy: "PerkOSは事業の意図とAI実行をつなぐコントロールプレーンです。文脈、チーム、ワークフロー、承認、証拠、基盤を一つにします。", center: "運用レイヤー", rails: ["事業コンテキスト", "人 + エージェント", "制御 + 信頼", "成果 + 証拠"] },
  loop: { ...en.loop, section: "システム", kicker: "PerkOSの仕組み", title: "単発ツールではなく、", accent: "連続する運用ループ。", steps: [["発見", "事業を理解し、最も価値の高い機会を見つけます。"], ["設計", "証拠を非公開の構造化ブループリントに変換します。"], ["編成", "役割、知識、ツール、ランタイムを設定します。"], ["運用", "プロジェクト、タスク、チャット、承認を調整します。"], ["改善", "成果を次の導入に反映します。"]], cycle: "次のサイクルへ", principles: [["事業を先に", "モデルではなく測定可能なニーズから始めます。"], ["人が制御", "承認と境界を明確に保ちます。"], ["ランタイム中立", "PerkOS管理または外部AIを利用できます。"]] },
  surfaces: { ...en.surfaces, section: "製品アーキテクチャ", kicker: "製品サーフェス", title: "3つのサーフェス。", accent: "1つのシステム。", items: [{ label: "01 · 発見", title: "PerkOS Grow", copy: "適応型診断がニーズを機会マップ、レポート、機械可読の非公開アーティファクトへ変換します。", foot: "公開入力 · 人向けレポート · 内部JSON" }, { label: "02 · 運用", title: "PerkOS App", copy: "組織がチームを起動し、プロジェクトとタスクを管理し、文脈を保ち、全参加者と連携します。", foot: "プロジェクト · タスク · 文書 · チャット · 承認" }, { label: "03 · 接続", title: "PerkOS Infrastructure", copy: "モデルを強制せず、管理エージェントとOpenClaw、Hermes、カスタムランタイムを接続します。", foot: "A2A · モデルゲートウェイ · Knowledge · ID · 決済" }], summary: "各サーフェス単体でも価値があり、連携すると発見から運用までの循環になります。" },
  live: { ...en.live, section: "実行", kicker: "構築済み・稼働中", title: "現在すでに", accent: "稼働しているもの。", badge: "本番基盤", intro: "現在のプラットフォームは発見、運用、ランタイム接続、文脈、モデル、知識をカバーしています。次はそれらを再現可能な顧客体験へ統合します。", items: [["適応型ディスカバリー", "Grow面談、メール認証、多言語レポート、非公開PDFとJSON。"], ["プロジェクト運用", "組織、プロジェクト、タスク、文書、直接・プロジェクトチャット、チーム。"], ["外部ランタイム", "OpenClawとHermesの公式導入・修復、双方向PerkOS Chat。"], ["コンテキストプレーン", "実行前にプロジェクト、会話、チーム、タスク、証拠の正しい文脈を提供。"], ["モデルゲートウェイ", "複数プロバイダーのルーティング、計測、同時実行制御、BYOM。"], ["Knowledgeレイヤー", "調査依頼、証拠、検索、再利用可能な組織知識。"]], note: "「稼働中」は導入済み機能と本番受入テストを指し、売上や顧客数を意味しません。" },
  proof: { ...en.proof, section: "アーキテクチャ実証", kicker: "PerkOS Council", title: "演出されたチャットではなく、", accent: "実在する異種AIチーム。", team: "プロジェクトチーム", connected: "接続済み", roles: ["OpenClaw · コーディネーター", "OpenClaw · 外部", "OpenClaw · 外部", "Hermes · 外部", "OpenClaw · 外部", "OpenClaw · 外部"], model: "モデル選択はランタイム側が保持。PerkOSはエージェントのモデルを強制せず仕事を調整します。", items: [["双方向通信", "プロジェクトチャットから外部ランタイムへ届き、返信が同じ会話へ戻ります。"], ["正しいコンテキスト", "各実行が最新のチーム、調整役、タスク、文書、会話範囲を受け取ります。"], ["設計段階の分離", "テナント、プロジェクト、会話、認証、ランタイム境界で混在を防ぎます。"]] },
  business: { ...en.business, section: "ビジネスモデル", kicker: "商用エンジン", title: "課題から入り、", accent: "成果で拡大する。", intro: "二つのニッチは同じ買い方をします。目に見える高コストのボトルネックを抱えた小規模事業、一度の会話で決める経営者、そして数週間で回収できるか否かがはっきりする業務です。", phases: [["入口", "診断", "業務を一つに絞り、数値で測ります。週あたりの予約確定数、または日あたりの見積もり返答数です。"], ["導入", "展開", "診療所もカウンターも、自分の診療枠、カタログ、価格表、承認ルールのまま稼働を始めます。"], ["継続", "運用", "チームは毎日、同じ受信箱、同じボード、同じ承認に戻ります。利用は事業とともに伸びます。"], ["拡大", "蓄積", "予約の次は再来促進と請求へ。見積もりの次は発注と売掛管理へ広がります。"]], revenues: ["導入と業務設定", "診療所・拠点あたりの月額運用", "チャネルパートナーと業種特化ソフト"] },
  gtm: { ...en.gtm, section: "市場展開", kicker: "二つの橋頭堡", title: "痛みが明確な場所から始め、", accent: "繰り返せるものを拡大。", wedgeTitle: "入口は業種の一覧ではなく、二つのニッチです。", wedge: "独立系の診療所と、整備工場にB2Bで卸す自動車部品店。どちらも小規模で、経営者が決め、人が手作業で翻訳している受信依頼の上に成り立っています。", grow: "Growが入口です。事業を見極め、そのまま導入のブリーフになる診断を行います。", stages: [["独立系の診療所", "医師一名から五名の規模。受付が患者と診療枠の間に立ち、無断キャンセルが枠を丸ごと失わせます。"], ["自動車部品店", "整備工場に卸すカウンター。最初に見積もった側が受注し、カタログは誰かの頭の中にあります。"], ["チャネルパートナー", "すでにこれらの事業の内側にいる人たち。予約管理ソフト、部品カタログ提供者、会計士、地域のコンサルタントです。"], ["テンプレート循環", "導入ごとに次のプレイブックが鋭くなり、十件目は一件目のわずかな手間で済みます。"]] },
  moat: { ...en.moat, section: "競争優位", kicker: "蓄積する優位性", title: "防御力は", accent: "閉じたループにある。", intro: "単機能は模倣できます。PerkOSは発見、設計、実行文脈、相互運用、検証可能な運用を横断して蓄積します。", layers: [["発見データ", "企業が本当に必要とするものの構造化された証拠。"], ["ソリューション設計", "ニーズ、役割、フローを結ぶ再利用可能な非公開パターン。"], ["コンテキストプレーン", "最新のプロジェクト情報を各ランタイムへ安全に提供。"], ["ランタイムネットワーク", "モデルロックインなしで管理・外部エージェントを接続。"], ["信頼レール", "ID、認可、利用、レシート、任意の決済。"]], flywheel: "導入増加 → 設計改善 → 成果高速化 → 流通強化。", compound: "蓄積システム", layer: "レイヤー" },
  roadmap: { ...en.roadmap, section: "ロードマップ", kicker: "これから", title: "次の", accent: "12か月。", badge: "将来計画", intro: "既存製品をつなぎ、成功したソリューションを再現可能、スケーラブル、そして継続的に改善するものへ進化させます。", focuses: ["発見から導入までを閉じる", "ソリューションを再現可能に", "運用レイヤーを拡張", "ネットワークへ蓄積"], details: [["PerkOS内のネイティブGrow", "非公開設計と人のレビュー", "オンボーディングと可観測性統合"], ["業界別ソリューション", "成果測定ループ", "デザインパートナー導入手順"], ["大規模マルチテナント運用", "非公開ソリューションカタログ", "利用・請求・パートナー制御"], ["自己改善するソリューション網", "組織間エージェントサービス", "任意のM2Mコマース"]] },
  close: { ...en.close, kicker: "ビジョン", title: "すべての企業が", accent: "AIチームと運営できる未来。", copy: "PerkOSは、最初の質問から稼働チームまで、事業の意図を責任あるAIの仕事に変えるシステムを構築しています。", explore: "PerkOSを見る", partners: ["デザインパートナー", "エコシステムパートナー", "投資家"] },
};

const ko: DeckCopy = {
  ...ja,
  nav: { deck: "투자자 덱", present: "프레젠테이션", slides: "장 · 원하는 슬라이드에서 시작하세요", hint: "진지하고 간결한 투자자 대화용 · 재무 금액 없음", next: "다음 슬라이드", previous: "이전 슬라이드", exit: "프레젠테이션 종료", investorOverview: "투자자 개요" },
  hero: { eyebrow: "실제 업무를 수행하는 AI 팀", title: "비즈니스 문제에서", accent: "책임 있는 AI 팀으로.", copy: "PerkOS는 AI가 가치를 만들 지점을 찾고, 적합한 팀을 구성하며, 그 팀이 실제로 일할 운영 계층을 제공합니다." },
  problem: { ...ja.problem, section: "문제", kicker: "두 니치, 같은 격차", title: "AI 도입에는", accent: "번역의 격차가 있습니다.", intro: "전혀 닮지 않은 두 사업을 봅니다. 독립 의원과, 정비소에 납품하는 자동차 부품 도매상입니다. 둘은 정확히 같은 지점에서 매출을 잃습니다.", items: [["일은 메시지로 도착합니다", "환자는 진료 예약을 묻고, 정비소는 그 부품이 2018년식에 맞는지 묻습니다. 어느 쪽도 정형 데이터로 오지 않습니다."], ["답변에는 고유한 맥락이 필요합니다", "진료 일정과 보험 규정에 달려 있거나, 카탈로그와 재고와 그 거래처의 단가표에 달려 있습니다."], ["한 사람이 병목입니다", "접수는 환자를 기다리게 한 채 전화를 받습니다. 카운터가 한 곳에 견적을 내는 동안 세 곳이 답을 기다립니다."], ["늦은 답변은 잃은 매출입니다", "확정되지 않은 예약은 노쇼가 되고, 두 시간 걸린 견적은 남의 매출이 됩니다."]], insight: "공통점이 전혀 없는 두 업종에 같은 운영 형태가 있습니다. 정리되지 않은 수요와 고유한 맥락, 그 사이에 선 한 사람입니다." },
  thesis: { ...ja.thesis, section: "투자 논지", kicker: "우리의 논지", title: "모델이 곧 제품은 아닙니다.", accent: "그 주변의 운영체제가 제품입니다.", copy: "PerkOS는 비즈니스 의도와 AI 실행 사이의 컨트롤 플레인입니다. 맥락, 팀, 워크플로, 승인, 증거, 인프라를 하나로 연결합니다.", center: "운영 계층", rails: ["비즈니스 맥락", "사람 + 에이전트", "통제 + 신뢰", "성과 + 증거"] },
  loop: { ...ja.loop, section: "시스템", kicker: "PerkOS 작동 방식", title: "또 하나의 단일 도구가 아닌,", accent: "연속적인 운영 루프.", steps: [["발견", "비즈니스를 이해하고 가장 가치 높은 기회를 찾습니다."], ["설계", "증거를 비공개 구조화 블루프린트로 바꿉니다."], ["구성", "역할, 지식, 도구, 런타임을 설정합니다."], ["운영", "프로젝트, 업무, 채팅, 승인을 조율합니다."], ["개선", "성과를 다음 배포에 반영합니다."]], cycle: "다음 사이클로 연결", principles: [["비즈니스 우선", "모델이 아닌 측정 가능한 필요에서 시작합니다."], ["사람의 통제", "승인과 경계를 명확히 유지합니다."], ["런타임 중립", "PerkOS 관리형 또는 외부 AI를 사용합니다."]] },
  surfaces: { ...ja.surfaces, section: "제품 아키텍처", kicker: "제품 영역", title: "세 개의 영역.", accent: "하나의 시스템.", items: [{ label: "01 · 발견", title: "PerkOS Grow", copy: "적응형 진단이 요구를 기회 지도, 보고서, 기계가 읽는 비공개 아티팩트로 전환합니다.", foot: "공개 입력 · 사용자 보고서 · 내부 JSON" }, { label: "02 · 운영", title: "PerkOS App", copy: "조직이 팀을 시작하고, 프로젝트와 업무를 조율하며, 맥락을 유지하고 모든 참여자와 소통합니다.", foot: "프로젝트 · 업무 · 문서 · 채팅 · 승인" }, { label: "03 · 연결", title: "PerkOS Infrastructure", copy: "모델을 강제하지 않고 관리형 에이전트와 OpenClaw, Hermes, 커스텀 런타임을 연결합니다.", foot: "A2A · 모델 게이트웨이 · Knowledge · 신원 · 결제" }], summary: "각 영역은 독립적으로 가치가 있고, 함께 발견에서 운영까지의 순환을 만듭니다." },
  live: { ...ja.live, section: "실행", kicker: "구축 및 운영 중", title: "현재 이미", accent: "운영 중인 기반.", badge: "프로덕션 기반", intro: "플랫폼은 이미 발견, 운영, 런타임 연결, 맥락, 모델, 지식을 포괄합니다. 다음 단계는 이를 반복 가능한 고객 여정으로 연결하는 것입니다.", items: [["적응형 발견", "Grow 인터뷰, 이메일 인증, 다국어 보고서, 비공개 PDF와 JSON."], ["프로젝트 운영", "조직, 프로젝트, 업무, 문서, 직접·프로젝트 채팅, 팀."], ["외부 런타임", "OpenClaw와 Hermes 공식 설치·복구 및 양방향 PerkOS Chat."], ["컨텍스트 플레인", "실행 전 프로젝트, 대화, 팀, 업무, 증거의 정확한 맥락 제공."], ["모델 게이트웨이", "다중 제공자 라우팅, 계측, 동시성 제어, 자체 모델 지원."], ["Knowledge 계층", "리서치 요청, 증거, 검색, 재사용 가능한 조직 지식."]], note: "‘운영 중’은 배포된 기능과 프로덕션 승인 테스트를 뜻하며 매출이나 고객 규모를 의미하지 않습니다." },
  proof: { ...ja.proof, section: "아키텍처 검증", kicker: "PerkOS Council", title: "연출된 챗봇 데모가 아닌,", accent: "실제 이기종 AI 팀.", team: "프로젝트 팀", connected: "연결됨", roles: ["OpenClaw · 코디네이터", "OpenClaw · 외부", "OpenClaw · 외부", "Hermes · 외부", "OpenClaw · 외부", "OpenClaw · 외부"], model: "모델 선택은 런타임이 소유합니다. PerkOS는 에이전트의 모델을 강제하지 않고 업무를 조율합니다.", items: [["양방향 통신", "프로젝트 채팅에서 외부 런타임으로 전달되고 답변이 같은 대화에 돌아옵니다."], ["신뢰 가능한 맥락", "각 실행은 최신 팀, 코디네이터, 업무, 문서, 대화 범위를 받습니다."], ["설계된 격리", "테넌트, 프로젝트, 대화, 자격 증명, 런타임 경계가 사용자 혼합을 막습니다."]] },
  business: { ...ja.business, section: "비즈니스 모델", kicker: "상업 엔진", title: "문제로 진입하고,", accent: "성과로 확장합니다.", intro: "두 니치는 같은 방식으로 구매합니다. 눈에 보이고 비용이 큰 병목을 가진 소규모 사업, 한 번의 대화로 결정하는 대표, 그리고 몇 주 안에 회수되거나 아예 안 되는 업무입니다.", phases: [["진입", "진단", "업무 하나만, 숫자로 측정합니다. 주당 확정된 예약, 또는 하루에 회신한 견적입니다."], ["출시", "배포", "의원도 카운터도 자기 일정, 카탈로그, 단가표, 승인 규칙 그대로 가동을 시작합니다."], ["반복", "운영", "팀은 매일 같은 수신함, 같은 보드, 같은 승인으로 돌아옵니다. 사용량은 사업과 함께 늘어납니다."], ["확장", "축적", "예약 다음은 재내원과 청구로, 견적 다음은 발주와 미수금 관리로 넓어집니다."]], revenues: ["구축 및 업무 설정", "의원 또는 지점당 월 운영", "채널 파트너와 업종 특화 소프트웨어"] },
  gtm: { ...ja.gtm, section: "시장 진출", kicker: "두 개의 교두보", title: "고통이 구체적인 곳에서 시작해", accent: "반복되는 것을 확장합니다.", wedgeTitle: "진입점은 업종 목록이 아니라 두 개의 니치입니다.", wedge: "독립 의원과, 정비소에 B2B로 납품하는 자동차 부품 도매상. 둘 다 규모가 작고, 대표가 결정하며, 사람이 손으로 번역해야 하는 인바운드 요청 위에서 돌아갑니다.", grow: "Grow가 정문입니다. 사업을 선별하고 그대로 배포 브리프가 되는 진단을 수행합니다.", stages: [["독립 의원", "의사 1~5인 규모. 접수가 환자와 진료 일정 사이에 서 있고, 노쇼 하나가 진료 슬롯 전체를 없앱니다."], ["자동차 부품 도매상", "정비소에 납품하는 카운터. 먼저 견적을 낸 쪽이 주문을 가져가고, 카탈로그는 누군가의 머릿속에 있습니다."], ["채널 파트너", "이미 이 사업 안에 있는 사람들. 예약 관리 소프트웨어, 부품 카탈로그 공급사, 회계사, 지역 컨설턴트입니다."], ["템플릿 순환", "배포할 때마다 다음 플레이북이 날카로워지고, 열 번째는 첫 번째의 일부 비용으로 끝납니다."]] },
  moat: { ...ja.moat, section: "방어력", kicker: "누적되는 우위", title: "해자는", accent: "닫힌 루프입니다.", intro: "단일 기능은 복제할 수 있습니다. PerkOS는 발견, 설계, 실행 맥락, 상호운용성, 검증 가능한 운영 전반에서 우위를 축적합니다.", layers: [["발견 데이터", "기업이 실제로 필요로 하는 것에 대한 구조화된 증거."], ["솔루션 블루프린트", "요구, 역할, 워크플로를 잇는 재사용 가능한 비공개 패턴."], ["컨텍스트 플레인", "최신 프로젝트 사실을 각 런타임에 안전하게 전달."], ["런타임 네트워크", "모델 종속 없이 관리형·외부 에이전트를 연결."], ["신뢰 레일", "신원, 권한, 사용, 영수증, 선택적 결제."]], flywheel: "더 많은 배포 → 더 나은 설계 → 더 빠른 성과 → 더 강한 유통.", compound: "누적 시스템", layer: "계층" },
  roadmap: { ...ja.roadmap, section: "로드맵", kicker: "앞으로의 방향", title: "다음", accent: "12개월.", badge: "향후 계획", intro: "현재 제품을 연결하고 성공한 솔루션을 반복 가능하고 확장 가능하며 지속적으로 개선되는 시스템으로 발전시킵니다.", focuses: ["발견에서 배포까지 연결", "솔루션 반복 가능화", "운영 계층 확장", "네트워크로 축적"], details: [["PerkOS 내 네이티브 Grow", "비공개 설계와 사람 검토", "온보딩·관측성 통합"], ["산업별 솔루션 템플릿", "성과 측정 루프", "디자인 파트너 배포 절차"], ["대규모 멀티테넌트 조율", "비공개 솔루션 카탈로그", "사용·청구·파트너 통제"], ["스스로 개선되는 솔루션망", "조직 간 에이전트 서비스", "선택적 M2M 커머스"]] },
  close: { ...ja.close, kicker: "비전", title: "모든 기업이", accent: "AI 팀과 함께 운영되는 미래.", copy: "PerkOS는 첫 질문부터 운영 팀까지 비즈니스 의도를 책임 있는 AI 업무로 바꾸는 시스템을 구축합니다.", explore: "PerkOS 살펴보기", partners: ["디자인 파트너", "생태계 파트너", "투자자"] },
};

export const DECK_COPY: Record<PublicDeckLanguage, DeckCopy> = { en, es, fr, pt, ja, ko };

export function useDeckCopy() {
  const { i18n } = useTranslation();
  const candidate = (i18n.resolvedLanguage || i18n.language || "en").split("-")[0] as PublicDeckLanguage;
  const language: PublicDeckLanguage = candidate in DECK_COPY ? candidate : "en";
  return { copy: DECK_COPY[language], language };
}

